### ISSUE TITLE
Crossover Screen:  Does not seem to be changing as expected.

### ISSUE THREAD

**Issue by rgleason** [seandepagnier/weather_routing_pi#100]
The crossover screen seems to the working, at least it is showing stuff, but I am not quite sure what I am looking at, and when I highlight different polar files in the boat file, shouldn't the crossover chart change?

![screenshot 107](https://user-images.githubusercontent.com/2363959/34240836-239d0bee-e5df-11e7-9d03-a74cbe85b328.png)

**Comment by rgleason** [comment]
Crossover Chart does not change if the "Overlap %" is Changed either.

**Comment by rgleason** [comment]
I believe the Crossover Information is missing.

The graphic does change if I remove a polar file, and then another leaving TWS-0-6.pol. See screenshots. There are also other changes depending on the dropdown data selections and the TAB selected, but I think some information is missing because changing the Crossover % does not change anything.  

I am going to upload various screenshots since I don't know what this is supposed to look like.

![screenshot 109](https://user-images.githubusercontent.com/2363959/34263792-af49ecca-e63e-11e7-9fef-f9aed7af4591.png)
![screenshot 111](https://user-images.githubusercontent.com/2363959/34263824-c84c9f42-e63e-11e7-83d0-4ef1f3508935.png)
![screenshot 112](https://user-images.githubusercontent.com/2363959/34263833-cd7b427a-e63e-11e7-9d36-b1ec15911386.png)
![screenshot 113](https://user-images.githubusercontent.com/2363959/34263836-d1411b5a-e63e-11e7-9dfe-5651efb4fce3.png)
![screenshot 114](https://user-images.githubusercontent.com/2363959/34263842-d5e5f360-e63e-11e7-9400-67dac804d26c.png)
![screenshot 122](https://user-images.githubusercontent.com/2363959/34264050-86963102-e63f-11e7-8873-d9e09b1efbd7.png)
![screenshot 123](https://user-images.githubusercontent.com/2363959/34264051-8c22b956-e63f-11e7-8b15-fc37f204560a.png)
![screenshot 115](https://user-images.githubusercontent.com/2363959/34263850-dc374796-e63e-11e7-9f71-0f597174112b.png)
![screenshot 117](https://user-images.githubusercontent.com/2363959/34263856-e1e490cc-e63e-11e7-99a6-a7d2f967e9f4.png)
![screenshot 118](https://user-images.githubusercontent.com/2363959/34263876-ebb40ea2-e63e-11e7-82c7-208fd898bbc3.png)
![screenshot 119](https://user-images.githubusercontent.com/2363959/34263883-f111fc06-e63e-11e7-9e37-de032fa5cbde.png)
![screenshot 120](https://user-images.githubusercontent.com/2363959/34264008-695be1cc-e63f-11e7-8c6e-be568c2bfaa6.png)

Finally I am getting a change!

![screenshot 121](https://user-images.githubusercontent.com/2363959/34264014-6c8e7d78-e63f-11e7-8b5d-9e510f7e5dc1.png)

**Comment by rgleason** [comment]
The Crossover does not show any real changes until the % gets up to between 15-20%.  Is this true?

How would we see the crossover % for the TWS-0-6.pol  range?  It seems so small and inconsequential. Why doesn't the scale change on crossover when the user highlights the Polar? Say TWS-0-6?

**Comment by rgleason** [comment]
I tried driving the crossover up for all the 3 polars and started to get another color..
I don't know if this is working yet, but it seems like the crossovers should for less % perhaps 5-15% but maybe I am wrong here. How can this be useful this way I wonder?

![screenshot 128](https://user-images.githubusercontent.com/2363959/34264609-76f7f7e2-e641-11e7-8d28-152f91fde2e9.png)

**Comment by seandepagnier** [comment]
The crossover won't work with overlap unless both polars define a boat
speed in that region.

For example, if you define from 0-6 and 6-20 knots, then no matter
what overlap %, no overlap can occur.

You would need a polar that defines from 0-10, then from 6-20, to see
some kind of meaningful overlap.

Sean

**Comment by rgleason** [comment]
OK, good point.  I hadn't thought about that. 
I'll modify the example polars to show that better.  (You haven't accepted them yet anyway.)

I suppose I should make a note about this in wiki too.

**Comment by rgleason** [comment]
I think it's time to close this, but make additional notes and screenshots in the wiki.
