### ISSUE TITLE
Grib wind speed exceeds polar data.

### ISSUE THREAD

**Issue by rgleason** [seandepagnier/weather_routing_pi#11]
Grib wind speed exceeds polar data and there is a failure.

Some ways to handle it:
1. Display a warning in the status that maximum wind for the specified polar had been exceeded?
2. Use the unknown polar upper wind speeds as constraint with a message "polar upper limit reached, now routing around the higher winds" and the config constraint table shows that wind speed as an upper limit.

See #7 Calculation on Grib alone fails.  Norulz   David

**Comment by seandepagnier** [comment]
I believe I implemented this

**Comment by rgleason** [comment]
Ok I'll close it.
