### ISSUE TITLE
wrdc compile failure on OSX

### ISSUE THREAD

**Issue by lanceberc** [seandepagnier/weather_routing_pi#12]
Using MACOSX_DEPLOYMENT_TARGET=10.7 compiling weather_routing_pi fails to find an include file.

================

[ 94%] Building CXX object CMakeFiles/weather_routing_pi.dir/src/wrdc.cpp.o
/Users/lance/src/plugins/weather_routing_pi/src/wrdc.cpp:44:18: fatal error: 'GL/gl.h' file not found
        #include <GL/gl.h>
                 ^
1 error generated.
make[2]: *** [CMakeFiles/weather_routing_pi.dir/src/wrdc.cpp.o] Error 1
make[1]: *** [CMakeFiles/weather_routing_pi.dir/all] Error 2
make: *** [all] Error 2

================

After copying gl.h, glext.h, and glu.h from OpenCPN/include/GL to weather_routing_pi/include/GL it compiles and runs.

================

OpenCPN ships with 6 different copies of "gl.h"! I hope I copied the right versions.

$ find OpenCPN -name "gl.h"
OpenCPN/include/GL/gl.h
OpenCPN/src/glshim/include/GL/gl.h
OpenCPN/src/glshim/include/GLES/gl.h
OpenCPN/src/glshim/src/gl/gl.h
OpenCPN/src/glshim/src/gl/wrap/gl.h
OpenCPN/src/glshim/src/proxy/gl.h

**Comment by seandepagnier** [comment]
did you ever resolve this?

I think gl.h is in a different location on osx

**Comment by rgleason** [comment]
I think this is fixed now. Can it be closed?

**Comment by rgleason** [comment]
Sean, did you see Lanceberc's two pull requests.
