### ISSUE TITLE
WxRte Configuration - Time - Decimal point on Minutes.

### ISSUE THREAD

**Issue by rgleason** [seandepagnier/weather_routing_pi#125]
Small thing:

>The accuracy to the second with a decimal point on the minutes is not of any use but not dangerous, just confusing

Maybe we should fix this, so it's good.

![wxrte-time](https://user-images.githubusercontent.com/2363959/35278456-1ab3cc04-0018-11e8-82a6-0906da6fbf23.png)

.

**Comment by nohal** [comment]
This is IMO fixed by the switch to `wxTimePickerCtrl`, the second accuracy is of course completely useless for this application, but we could then keep going and think the same about minutes and end up asking for quarters or halves of an hour as a unit...

**Comment by rgleason** [comment]
Yes. Thanks
