### ISSUE TITLE
Route fails with some polar which seems correct

### ISSUE THREAD

**Issue by dominig** [seandepagnier/weather_routing_pi#127]
I calculate the same route with the same grib going from Paimpol in Brittany to Plymouth in UK.
Both polar looks correct but with the elan polar it crashes while with the A35 is complete its calculation.
Both polar are attached in the zip file.
[2polars.zip](https://github.com/seandepagnier/weather_routing_pi/files/1656997/2polars.zip)

See snapshot.
![screenshot_20180123_181437](https://user-images.githubusercontent.com/1193120/35291087-8426b0f8-006c-11e8-81e2-6d1a6d88ae4a.png)
![screenshot_20180123_183257](https://user-images.githubusercontent.com/1193120/35291088-844fa602-006c-11e8-8810-bac973074535.png)

**Comment by seandepagnier** [comment]
Does the program crash, or does the routing fail to complete?

**Comment by dominig** [comment]
The route calculation seems to complete (the progressing bar) then the route starts to be displayed and then hangs and leaves the screen half gray with a partial route drawn, as you can see on the first snapshot.

**Comment by seandepagnier** [comment]
So you are forced to restart opencpn?

**Comment by rgleason** [comment]
Dominig,  
I downloaded the two polars.  elan340.csv and tried it. It did not work for me. I checked it by highlighting it in the Boat file I created and then hit Edit.  There were true wind columns that were zeros. This is not allowed, so I removed all the true wind columns that were 0 using the "Dimensions Tab"  
(Sean this is really nice and easy! No troubles counting or deciphering things as with Notepad++!)
Then tried the polar file and it seems to work, but I noted that it only goes up to 20 knots, so the polar does not successfully route when there are gribs with heavier winds. You could add a second Elan340-heavy-wind which has your storm sails to have more "completed" routings.

See screenshots and attached revised polar.
This is the original polar
![screenshot 360](https://user-images.githubusercontent.com/2363959/35307454-e268efa6-0070-11e8-808b-a64c44b17492.png)

This is the revised polar
![screenshot 359](https://user-images.githubusercontent.com/2363959/35307469-f22d6dae-0070-11e8-8ded-62560f5b5803.png)

Attached is the revised polar.
[Elan340-revised.csv.txt](https://github.com/seandepagnier/weather_routing_pi/files/1658053/Elan340-revised.csv.txt)

Original Polar.
[Elan340-doming.csv.txt](https://github.com/seandepagnier/weather_routing_pi/files/1658054/Elan340-doming.csv.txt)

**Comment by seandepagnier** [comment]
hmm....    It should still work with the zeros, just not choosing
those courses... so this is a minor bug.   Unless I can fix it,  I
need to make a warning to the user.

**Comment by rgleason** [comment]
Thanks Sean. I know you tried to have wxrte injest such polars and fix them.

**Comment by rgleason** [comment]
Dominiq, its minor, but there was an anomaly in the elan file.  it is 47 degrees at 10 knots, has 4.7. I have changed that to 6.6. 

![screenshot 371](https://user-images.githubusercontent.com/2363959/35335709-4a86d530-00e4-11e8-95d2-e5d746f3cf0b.png)

**Comment by rgleason** [comment]
Can we close this now dominiq? 
I believe the answer is above.  You or Sean must close it.

**Comment by rgleason** [comment]
Dominiq, its minor, but there was an anomaly in the elan file. it is 47 degrees at 10 knots, has 4.7. I have changed that to 6.6.

I changed the value and it works now.   The Graph anomaly/discontinuity is clearly visible and is what caused the failure.

Can we please close this now.
