### ISSUE TITLE
ComputeBoatSpeed in high(er) winds

### ISSUE THREAD

**Issue by lanceberc** [seandepagnier/weather_routing_pi#14]
Weather routing fails if the wind is higher than what the polars model with a (at first mysterious) Polar: Failed message. This is a problem around here since most of OpenCPNs models stop at 16kts or 20kts and it blows more than that regularly around here in the summer. I don't know what the "right" solution is; for now I've hacked a loop in RouteMap.cpp:ComputeBoatSpeed() looking for the max wind velocity supported.

        if(configuration.ClimatologyType == RouteMapConfiguration::CUMULATIVE_MINUS_CALMS)
            VB *= 1-atlas.calm;
       } else {
           // If there's no defined speed for this heading, maybe the wind strength is
           // more than what's modeled. Search for polar data at a lower wind velocity
           double c = VW;
           while (c > 0) {
               VB = plan.Speed(H, c);
               if (!isnan(VB)) break;
               c -= 0.25;
           }
           if (isnan(VB))
               printf("RouteMap:ComputeBoatSpeed: No Polar for wind %f kts @ %f degrees\n", VW, H);
           else
               if (c != VW)
                   printf("RouteMap:ComputeBoatSpeed: Estimating speed with wind %f kts @ %f to wind %f kts speed %f\n",
                      VW, H, c, VB);
       }

**Comment by rgleason** [comment]
Lancberc thanks. You perhaps experienced this when there was just a "failed" message? "Polar failed is a step in the rigjt direction and your extension also helps, but shouldn't we be extending the boat"s polar?

Maybe that should also be in the nessage!
Polar failed. Extend polar range.

I suppose you could also bump the speed up by  some small proportional factor but some boats reduce sail and get slower, so the skipper reallly should be making or using anotherv or different pilar.

I think what you've done is good.

**Comment by rgleason** [comment]
Does it work? Where does the code go?

**Comment by lanceberc** [comment]
Some boats get planing off the wind (think Volvo racer) and can maintain very high speeds for hours. Cruisers generally get slower when the wind is over 20kts as they reduce sail. I chose to use the highest modeled value as that's probably close to hull speed - if someone wants to use OpenCPN for weather routing a long distance ocean race in a sport boat they'll have to get more complete polars for their vessel.

Yes, the code change works - but Sean may have thought harder about this than I have and might have a better heuristic. It also only catches one reason why the polar failed - there may be others (I'd have to examine the code more closely). The printfs have to go - it really spews too many similar messages. AFAIK there's no equivalent of --verbose for OpenCPN.

"Polar: Failed" was a bit mysterious and prompted me to learn lots more about lldb (the OSX debugger) than the target OCPN user. The error message for the four failures in WeatherRouting.cpp that just say "Failed" - Grib, Climatology, Polar, and NoData, could be a bit more verbose - or documented. Not to take anything away from this awesome function.

**Comment by rgleason** [comment]
Lanceberc lucky you aren't a target user. Thanks. If you can give me a filename and line, i would try it.

**Comment by rgleason** [comment]
Agreed about brief msgs to user.

**Comment by rgleason** [comment]
Lancberc,
Sean did this 3 days ago.
 	use highest wind speed in polar above this speed 
https://github.com/seandepagnier/weather_routing_pi/commit/18f811735878e9acd2aa1e2ace282e5daa63d8c9
I will git fetch, compile for windows.

**Comment by rgleason** [comment]
Lanceberc
If it is working when you test this, would you please close this issue?
See the "Close this issue" at the bottom next to "Comment" !!
I cannot close it, because you opened it.

**Comment by rgleason** [comment]
Can this be closed now? Sean maybe you should just close it. I cant.
