### ISSUE TITLE
Feature request: Allow more user friendly stopping of routing computation

### ISSUE THREAD

**Issue by nohal** [seandepagnier/weather_routing_pi#147]
If the routing selected is currently being computed, change the "Compute" button label and function to "Stop".

Currently stopping the computation is available through the menu and using a keyboard shortcut, but users are obviously not able to find it.

**Comment by rgleason** [comment]
I'd like this improvement.!

**Comment by rgleason** [comment]
Also please add a  Single Reset button in addition to "Reset All"
