### ISSUE TITLE
Simultaneous editing of multiple configurations broken since PR #141 

### ISSUE THREAD

**Issue by nohal** [seandepagnier/weather_routing_pi#149]
https://github.com/seandepagnier/weather_routing_pi/commit/12454d9fad5ad202b62b7da688433c7730515bda#commitcomment-27644126 breaks the multiple configuration editing.

The time picker has to be invalidated and ignored if more than one configuration is selected (This is true if user does not use it to set time, if he does, all the configs have to be changed? Or?)

**Comment by seandepagnier** [comment]
Exactly.  That is how all the fields work.  If the user doesn't
change, it remains blank and each configuration keeps their time.
Once changed, all the configurations are updated.

This is a very convenient way to change one or more parameters across
many configurations as well as compare the similarities of selected
configurations

**Comment by nohal** [comment]
BTW, I don't know when you last actually tried this feature, but this is NOT how it works for dates even before #141...

**Comment by nohal** [comment]
I now also understand why the combos were an editable text field allowing completely invalid values - it was a hack to make this somehow work for positions...

**Comment by nohal** [comment]
That it worked for spin controls (it didn't as described, just "somehow") seems to rely on an obvious bug in wx3.0 where a disabled spin control is magically enabled on mouse-over. This bug is gone in wx3.1.

**Comment by stelian42** [comment]
What does this change for people still using wx3.0 ? Is wx3.1 becoming mandatory for OpenCPN and all the plugins ?

On my Ubuntu 17.10 system, it looks like wx3.1 isn't available yet (unless I use some extra ppa I suppose).

**Comment by nohal** [comment]
It means nothing, works exactly the same on wx3.1 and wx3.0 (at least on my systems). Unlike the original implementation that was broken on both, just differently.

**Comment by stelian42** [comment]
Ok, all good then.

**Comment by seandepagnier** [comment]
Yes it was broken for spin controls, sort of, using the disabled state.  This is not ideal but it seemed to sort of work.

It would be better to instead use a line edit, and a spin button, or implement a custom control.

**Comment by seandepagnier** [comment]
I just built and tested weather routing.

If two or more configurations selected do not have identical values for these fields, the controls should be blank to indicate this.


start and end position choices do not work correctly anymore:

We should insert a blank element into the combo dropdown to be used when all the elements don't agree.   If an actual position is selected, this blank element should be removed.

The spin controls used to rely on a hack to disable them.  This is not really ideal.  I think the solution involves using a line edit with numeric filter, and spin button.

The time picker still doesn't work either.  The date picker does work correctly.

**Comment by nohal** [comment]
> If two or more configurations selected do not have identical values for these fields, the controls should be blank to indicate this.

The fields that may be blank (= text fields) are blank, `wxSpinCtrl` does not support such stuff and never did. I definitely do not feel like reimplementing it because of this. 

> We should insert a blank element into the combo dropdown to be used when all the elements don't agree. If an actual position is selected, this blank element should be removed.

Although I do not fully agree, will implement it.

> The time picker still doesn't work either. The date picker does work correctly.

The only scenario I can reproduce here is hitting the "Current time" button, do you have some other as well?

**Comment by stelian42** [comment]
Regarding the time picker: look at the attached screencap: I selected the first two configurations, which have a starting time of 00:00:00 and 01:00:00. The editing window should give an empty time picker, it  shows instead 17:40:59 (which is my local time BTW)
![capture du 2018-02-19 17-41-50](https://user-images.githubusercontent.com/548364/36388527-6d3d1dc4-159c-11e8-811d-5cd5e9838312.png)

**Comment by nohal** [comment]
Yes, that is how the time picker control works. It can't be empty as far as I can tell (Neither ever is the date picker, for example on macOS). And the current time related logic was like that even before any changes (https://github.com/seandepagnier/weather_routing_pi/blob/v1.10.1/src/ConfigurationDialog.cpp#L148).

**Comment by seandepagnier** [comment]
I cannot build wxforumbuilder from git source.   It has issues with ticpp.

Did anyone succeed to build wxforumbuilder on a linux system?

**Comment by nohal** [comment]
I think @stelian42 has built it very recently.

**Comment by stelian42** [comment]
See: https://github.com/wxFormBuilder/wxFormBuilder/issues/301

**Comment by seandepagnier** [comment]
fixed
