### ISSUE TITLE
Optimal Route Wind Feathers

### ISSUE THREAD

**Issue by rgleason** [seandepagnier/weather_routing_pi#160]
They're a great addition. 
I'd like to see them better!!!
1. Choice of color.
2. Choice of Size.
3. Choice of weight.
4. Frequency
5. Distance off route.

Other possibilities.

Change color of route based upon boat speed. 
Set the range of colors to correspond with boat speeds in the polar.
Have a color scale = X knots.

Port & Starboard tacks shown on the route as a second colored (red or green) line alongside the optimal route.

**Comment by theeko74** [comment]
@rgleason 
About the different options you suggest:
1) Easy to do. Why not. It will add another option to the settings box.
2) and 3) are not so easy to implement.
4) Frequency is based on calculated step. If you choose 1h instead of 2h you will get twice wind arrow. I think this is sufficient.
5) Distance of route. Why not. Another option box.
6) Change the color of route based on calculated boat speed: Why not, but I do not see the benefit over plot chart. I also think that boat speed is not really important, average is enough. Maybe if you race but this is not my case ;-)
7) Port & starboard. I don't understand the point as normally the wind barrow much comes from the right of the track for starboard, left for port.

**Comment by rgleason** [comment]
1. Choice of color.- Easy to do. Why not. It will add another option to the settings box.
    4. Distance off the route. - Why not. Another option box.
    5. Change the color of route based on calculated boat speed: - Why not, but I do not see the benefit over plot chart. I also think that boat speed is not really important, average is enough. Maybe if you race but this is not my case ;-)   - OK, maybe you're right. - I'm interested in average boat speed for a step. Speed is visually shown by the distance between steps, but you don't really see the change, thus the idea to change the color. Is there some more important value to represent that way? say Wind speed?
    6. Port & starboard. I don't understand the point as normally the wind barrow much comes from the right of the track for starboard, left for port. - Yes of course, I had not seen that happen. That answers it, no need for this I think.

**Comment by seandepagnier** [comment]
Distance off route is confusing, why do we need that?

Also the line width of the route, or the color changing based on boat
speed might be interesting.
I have thought this could be interesting for opencpn tracks as well.

Could also show the route as green or red depending on starboard vs port tack.

**Comment by theeko74** [comment]
We can maybe draw the route with different color based on sail conditions. For example, let's say that at one point, you will meet strong wind, waves and you are sailing upwind, route can be in red. Otherwise, if you are sailing less windy, no wave, downwind, then the route can be in green.

![capture d ecran 2018-03-13 a 00 22 05](https://user-images.githubusercontent.com/22415254/37314554-177218f8-2655-11e8-8ea5-acb7e0c75c1c.png)

This can provide several benefits:
* visually see more difficulty conditions, and adapt the trip in consequence
* compare different routes and instantly see the most confortable route
* choose to delay the trip for a couple of hours to get a better weather window, etc.

What do you think?

**Comment by rgleason** [comment]
I like it! What do yo think Sean?

**Comment by seandepagnier** [comment]
I like it, but it requires a lot of options for the user to adjust

**Comment by rgleason** [comment]
Yes, but can it be simplified to something useful?

**Comment by theeko74** [comment]
The simplest way to do it is that maybe that there is only one option for the use, a box like "Show navigation comfort on route", and then takes default parameters like:
* Wind < 55 TWA && Wind Velocity > 17kn
* or waves > 1,5m && waves in front
* or Wind > 30kn
* or current > 2kn in front (<90°)

We can also define a mode for the user like: cruise (level 1), heavy sailor (level 2), race (level 3), to increase comfort threshold.

What do you think?

**Comment by rgleason** [comment]
Yes Sean, this would give us additional visual information about the trip and where to look at the Grib Weather Report more closely.  I really like it and I like the 3 levels idea.

**Comment by theeko74** [comment]
@seandepagnier 
Is there a simple way to get weather data (wind, waves, etc.) from a position?
I am using this code but it breaks:
````
RouteMapConfiguration configuration = GetConfiguration();
double dt = configuration.DeltaTime;

PlotData data;
Position *prev = pos->parent;
prev->GetPlotData(pos, dt, configuration, data);
````
With error at:
````
GribRecord *grh = grib->m_GribRecordPtrArray[Idx_HTSIGW];
>>> Thread 1: EXC_BAD_ACCESS (code=1, address=0xd8)
````
grh is NULL and I don't understand why... Any idea?

**Comment by seandepagnier** [comment]
See RouteMapOverlay::GetPlotData

You need to set the grib and time in the configuration before calling.

What are you trying to do exactly?  You shouldn't need to call this
unless you are trying to get data from positions not on the route.

**Comment by theeko74** [comment]
What I am trying ? Understand your code ;-)

If I understand correctly, `RouteMapOverlay::RenderCourse` is called to draw the weather route line in pink with the method `DrawLine(p, p->parent, dc, vp);`. In this method I want to call a method that will calculate the sailing condition level based on the position `p` (I will take position p weather data, and position `previous` to `p` weather data to calculate an average along these two points).

What do you think?

**Comment by seandepagnier** [comment]
If you are changing the width or color of the line, I suggest
calculating these values at each point.

From there, the line will change width and color along the segment.
Maybe need to use quads to render the line in this way though.


I think you can get the plot data from the points provided you pass
the grib and time in the configuration.

**Comment by theeko74** [comment]
> If you are changing the width or color of the line, I suggest
calculating these values at each point.

Yes, this is what I would like to do.

> I think you can get the plot data from the points provided you pass
the grib and time in the configuration.

So any idea why this code is not working?

`````
RouteMapConfiguration configuration = GetConfiguration();
double dt = configuration.DeltaTime;
    
PlotData data;
Position *prev = pos->parent;
prev->GetPlotData(pos, dt, configuration, data);
`````

**Comment by seandepagnier** [comment]
The configuration grib is not set.  You must set  before calling GetPlotData
                configuration.grib = (*it)->m_Grib;
                configuration.time = (*it)->time;

**Comment by theeko74** [comment]
I wrote this method to get back weather data (PlotData) based on position (lat,lon).

`````
PlotData RouteMapOverlay::getWeatherAtPosition(double lat, double lon)
{
    /* Method to get the weather data from a position
     * based on lat and lon.
     * (There is maybe another method but I could not
     * find it...).
     */
    
    std::list<PlotData> plot = GetPlotData(false);
    std::list<PlotData>::iterator it;
    for (it = plot.begin(); it != plot.end(); it++)
    {
        if (it->lat == lat && it->lon == lon)
            return *it;
    }
    return PlotData();  // Eq to python None?
}
`````
And before that:
`````
void RouteMapOverlay::RenderCourse(Position *pos, wxDateTime time, bool MarkAtPolarChange,
                                   wrDC &dc, PlugIn_ViewPort &vp)
{
...
DrawLine(p, p->parent, dc, vp);
PlotData data = getWeatherAtPosition(p->lat, p->lon);
...
`````

This is not working as it seams that `p->lat` is never egal to `it->lat`...
I am sorry, but I do not understand the way I can easily access to this data.

**Comment by theeko74** [comment]
OK I did with `last_destination_plotdata`...

````
PlotData RouteMapOverlay::getWeatherAtPosition(double lat, double lon)
{
    /* Method to get the weather data from a position
     * based on lat and lon.
     * (There is maybe another method but I could not
     * find it...).
     */
    
    std::list<PlotData>::iterator it;
    for (it = last_destination_plotdata.begin();
         it != last_destination_plotdata.end(); it++)
    {
        if (it->lat == lat && it->lon == lon)
            return *it;
    }
    return PlotData();  // Eq to python None?
}
````

**Comment by seandepagnier** [comment]
Sorry if it's confusing.   It's always difficult to read someone's program.   The weather routing is probably the most complicated plugin.

The weather is not just for a position, but also for a time, and even then, the source of the weather can vary.  So it's not possible to simply query by location.

I don't really think it makes sense to query it by the lat and lon.    Although it may work, you will have more code, and it will also be less efficient to run, although the speed is probabaly not important for this case.   Why not just iterate over the plot data and positions in parallel?

**Comment by theeko74** [comment]
Thanks, now I get it !

**Comment by theeko74** [comment]
<img width="617" alt="capture d ecran 2018-03-14 a 01 25 50" src="https://user-images.githubusercontent.com/22415254/37376859-bc2c5274-2726-11e8-8a6c-4683e80461bf.png">

Still few bugs with the color that I will correct tomorrow.

**Comment by rgleason** [comment]
Theeko  - super!

**Comment by skipperearly** [comment]
could the estim. date/time be added in the tooltip when hoovering over the track-route?

**Comment by rgleason** [comment]
Has anyone noticed slow/reluctant  panning, zooming and grab & drag?
I have with the most recent change. Don't know if it is something else about my computer, but it happens when using WxRte_pi with rendered route optimizations showing with optimal route feathers on and the most recent comfort indicator.  I should try it with these off too.

**Comment by rgleason** [comment]
May I close this great dialog?  Optimal Route wind feathers are working. Thank you guys great job!
Theeko74 you are a very effective programmer!

**Comment by theeko74** [comment]
Yes you can close

**Comment by rgleason** [comment]
Thanks theeko74  Great improvement.
