### ISSUE TITLE
FS#1779 - With grib open Route crashes during compilation

### ISSUE THREAD

**Issue by dominig** [seandepagnier/weather_routing_pi#17]
Not knowing where you prefer bug report, I double post this critical one.
   http://willkamp.com/opencpn/flyspray/index.php?do=details&task_id=1779

-----------------
Version:
OpenCPN
Stable 4.0
Weather routing Plugin
SHA 9a19a5aa45b3eabe70ebf47798392bc8cc300e9f
date 10 May 2015
Platform OpenSUSE 13.1

Start grib plugin and load a valid file
Start Weather routing
Create start and points
Hit Configuration > New
Leave all the default option
Close configuration window.
Hit Configuration > Compile
compilation slider open and progress until the end

Then it crashes

Console output
~> opencpn
ALSA lib pcm_dsnoop.c:618:(snd_pcm_dsnoop_open) unable to open slave
ALSA lib pcm_dmix.c:1022:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_dmix.c:961:(snd_pcm_dmix_open) The dmix plugin supports only playback stream
ALSA lib pcm_dmix.c:1022:(snd_pcm_dmix_open) unable to open slave
Cannot connect to server socket err = Aucun fichier ou dossier de ce type
Cannot connect to server request channel
jack server is not running or cannot be started

*** opencpn (wxWidgets 2.8.12) crashed ***, see backtrace!
0x7872e1 in wxCrashPrint::Report() at ??:?
0x536976 in MyApp::OnFatalException() at ??:?
0x7f622401a4cc in wxFatalSignalHandler at ??:0
0x7f62217239f0 in at ??:0
0x7f62213d7d1c in fseek at ??:0
0x6e075d in GshhsPolyCell::ReadPolygonFile() at ??:?
0x6e02fd in GshhsPolyCell::GshhsPolyCell(_IO_FILE*, int, int, PolygonFileHeader*) at ??:?
0x6e1df5 in GshhsPolyReader::crossing1(QLineF) at ??:?
0x6e4837 in GshhsReader::crossing1(QLineF) at ??:?
0x6e4640 in gshhsCrossesLand(double, double, double, double) at ??:?
0x709beb in PlugIn_GSHHS_CrossesLand at ??:?
0x7f61fb9fd2f0 in Position::CrossesLand(double, double) at ??:0
0x7f61fb9fc882 in Position::Propagate(std::list<IsoRoute*, std::allocator<IsoRoute*> >&, RouteMapConfiguration&) at ??:0
0x7f61fba016f2 in IsoRoute::Propagate(std::list<IsoRoute*, std::allocator<IsoRoute*> >&, RouteMapConfiguration&) at ??:0
0x7f61fba01d1d in IsoChron::PropagateIntoList(std::list<IsoRoute*, std::allocator<IsoRoute*> >&, RouteMapConfiguration&) at ??:0
0x7f61fba02e78 in RouteMap::Propagate() at ??:0
0x7f61fba0522e in RouteMapOverlayThread::Entry() at ??:0
0x7f6224016473 in wxThreadInternal::PthreadStart(wxThread*) at ??:0
0x7f622171c0db in at ??:0
0x7f622144cdad in clone at ??:0
Abandon

**Comment by seandepagnier** [comment]
do you have the world background data (gshhs) installed?  What detail level?

**Comment by dominig** [comment]
Le 18/06/2015 12:25, seandepagnier a écrit :
> do you have the world background data (gshhs) installed? What detail 
> level?
>
It seems that no OpenCPN packages provides gshhs.
I have them installed on the system but from ZyGrib.

Where would your plugin expects to find gshhs directory ?
which accuracy ?
do you have a propose url to upstream the data ?

Regards

Dominig

**Comment by seandepagnier** [comment]
The data is available as packages you can install with apt-get

Anyway.. I am concerned with the bug in weather routing plugin.

Can you confirm that if you do no have any charts you don't see the
world background map and in this case the plugin crashes?

**Comment by dominig** [comment]
Le 19/06/2015 12:27, seandepagnier a écrit :
> The data is available as packages you can install with apt-get
As I do the package for OpenSUSE, if I do not provide the file it will 
not exist.
I can con confirm that when I deactivate my chart, there is not cost 
outline at all.
So my question about where to find gshhs data and where to install them 
remains.
>
> Anyway.. I am concerned with the bug in weather routing plugin.
So do. I do have real chart :-)
>
> Can you confirm that if you do no have any charts you don't see the
> world background map and in this case the plugin crashes?
Yes, I see nothing and the crash log is as follow.

Dominig

*** opencpn (wxWidgets 2.8.12) crashed ***, see backtrace!
0x7872e1 in wxCrashPrint::Report() at ??:?
0x536976 in MyApp::OnFatalException() at ??:?
0x7f10847494cc in wxFatalSignalHandler at ??:0
0x7f1081e529f0 in  at ??:0
0x6e06f0 in GshhsPolyCell::ReadPolygonFile() at ??:?
0x6e02fd in GshhsPolyCell::GshhsPolyCell(_IO_FILE*, int, int, 
PolygonFileHeader*) at ??:?
0x6e1df5 in GshhsPolyReader::crossing1(QLineF) at ??:?
0x6e4837 in GshhsReader::crossing1(QLineF) at ??:?
0x6e4640 in gshhsCrossesLand(double, double, double, double) at ??:?
0x709beb in PlugIn_GSHHS_CrossesLand at ??:?
0x7f10600f62f0 in Position::CrossesLand(double, double) at ??:0
0x7f10600f5882 in Position::Propagate(std::list<IsoRoute*, 
std::allocator<IsoRoute*> >&, RouteMapConfiguration&) at ??:0
0x7f10600fa6f2 in IsoRoute::Propagate(std::list<IsoRoute*, 
std::allocator<IsoRoute*> >&, RouteMapConfiguration&) at ??:0
0x7f10600fad1d in IsoChron::PropagateIntoList(std::list<IsoRoute*, 
std::allocator<IsoRoute*> >&, RouteMapConfiguration&) at ??:0
0x7f10600fbe78 in RouteMap::Propagate() at ??:0
0x7f10600fe22e in RouteMapOverlayThread::Entry() at ??:0
0x7f1084745473 in wxThreadInternal::PthreadStart(wxThread*) at ??:0
0x7f1081e4b0db in  at ??:0
0x7f1081b7bdad in clone at ??:0
Abandon

**Comment by dominig** [comment]
More debug.
log from strace with no chart installed (gshhs is not there either).

strace -f -o opencpn.trace opencpn

as the trace is huge (31MB) I have just copied the end in the mail.

Dominig ar Foll
Senior Software Architect
Open Source Technology Centre
Intel SSG

31689 futex(0x1b326a8, FUTEX_WAIT_PRIVATE, 2, NULL <unfinished ...>
31747 <... close resumed> )             = 0
31689 <... futex resumed> )             = -1 EAGAIN (Resource temporarily unavailable)
31747 close(30 <unfinished ...>
31746 write(2, "[xcb] Unknown request in queue w"..., 47 <unfinished ...>
31747 <... close resumed> )             = 0
31689 futex(0x1b326a8, FUTEX_WAKE_PRIVATE, 1) = 0
31746 <... write resumed> )             = 47
31747 execve("/usr/lib64/mpi/gcc/openmpi/bin/addr2line", ["addr2line", "-e", "/proc/31689/exe", "-s", "0x7872e1", "0x536976", "0x7f52706b64cc", "0x7f526ddbf9f0
", "0x6e06f0", "0x6e02fd", "0x6e1df5", "0x6e4837", "0x6e4640", "0x709beb", "0x7f524c0f62f0", "0x7f524c0f5882", ...], [/* 102 vars */] <unfinished ...>
31746 write(2, "[xcb] Most likely this is a mult"..., 87 <unfinished ...>
31689 recvfrom(4,  <unfinished ...>
31746 <... write resumed> )             = 87
31747 <... execve resumed> )            = -1 ENOENT (No such file or directory)
31746 write(2, "[xcb] Aborting, sorry about that"..., 34 <unfinished ...>
31747 execve("/home/dominig/bin/addr2line", ["addr2line", "-e", "/proc/31689/exe", "-s", "0x7872e1", "0x536976", "0x7f52706b64cc", "0x7f526ddbf9f0", "0x6e06f0"
, "0x6e02fd", "0x6e1df5", "0x6e4837", "0x6e4640", "0x709beb", "0x7f524c0f62f0", "0x7f524c0f5882", ...], [/* 102 vars */] <unfinished ...>
31746 <... write resumed> )             = 34
31689 <... recvfrom resumed> 0x1b32704, 4096, 0, 0, 0) = -1 EAGAIN (Resource temporarily unavailable)
31747 <... execve resumed> )            = -1 ENOENT (No such file or directory)
31746 write(2, "opencpn: xcb_io.c\240:179\240:\240dequeue"..., 106) = 106
31746 mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f525800b000
31746 rt_sigprocmask(SIG_UNBLOCK, [ABRT], NULL, 8) = 0
31746 tgkill(31689, 31746, SIGABRT <unfinished ...>
31747 execve("/usr/local/bin/addr2line", ["addr2line", "-e", "/proc/31689/exe", "-s", "0x7872e1", "0x536976", "0x7f52706b64cc", "0x7f526ddbf9f0", "0x6e06f0", "
0x6e02fd", "0x6e1df5", "0x6e4837", "0x6e4640", "0x709beb", "0x7f524c0f62f0", "0x7f524c0f5882", ...], [/* 102 vars */] <unfinished ...>
31746 <... tgkill resumed> )            = 0
31689 poll([{fd=4, events=POLLIN|POLLOUT}], 1, 4294967295 <unfinished ...>
31747 <... execve resumed> )            = -1 ENOENT (No such file or directory)
31746 --- SIGABRT {si_signo=SIGABRT, si_code=SI_TKILL, si_pid=31689, si_uid=3204} ---
31747 execve("/usr/bin/addr2line", ["addr2line", "-e", "/proc/31689/exe", "-s", "0x7872e1", "0x536976", "0x7f52706b64cc", "0x7f526ddbf9f0", "0x6e06f0", "0x6e02
fd", "0x6e1df5", "0x6e4837", "0x6e4640", "0x709beb", "0x7f524c0f62f0", "0x7f524c0f5882", ...], [/* 102 vars */] <unfinished ...>
31701 <... select resumed> )            = ? <unavailable>
31702 +++ killed by SIGABRT +++
31716 +++ killed by SIGABRT +++
31704 +++ killed by SIGABRT +++
31703 +++ killed by SIGABRT +++
31701 +++ killed by SIGABRT +++
31700 +++ killed by SIGABRT +++
31693 +++ killed by SIGABRT +++
31692 +++ killed by SIGABRT +++
31746 +++ killed by SIGABRT +++
31747 <... execve resumed> )            = 0
31747 brk(0)                            = 0x11b9000
31747 mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fbd42ff5000
31747 access("/etc/ld.so.preload", R_OK) = -1 ENOENT (No such file or directory)
31747 open("/usr/lib64/mpi/gcc/openmpi/lib64/tls/x86_64/libbfd-2.25.0.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
31747 stat("/usr/lib64/mpi/gcc/openmpi/lib64/tls/x86_64", 0x7fff490c9f90) = -1 ENOENT (No such file or directory)
31747 open("/usr/lib64/mpi/gcc/openmpi/lib64/tls/libbfd-2.25.0.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
31747 stat("/usr/lib64/mpi/gcc/openmpi/lib64/tls", 0x7fff490c9f90) = -1 ENOENT (No such file or directory)
31747 open("/usr/lib64/mpi/gcc/openmpi/lib64/x86_64/libbfd-2.25.0.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
31747 stat("/usr/lib64/mpi/gcc/openmpi/lib64/x86_64", 0x7fff490c9f90) = -1 ENOENT (No such file or directory)
31747 open("/usr/lib64/mpi/gcc/openmpi/lib64/libbfd-2.25.0.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
31747 stat("/usr/lib64/mpi/gcc/openmpi/lib64", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
31747 open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
31747 fstat(3, {st_mode=S_IFREG|0644, st_size=216273, ...}) = 0
31747 mmap(NULL, 216273, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7fbd42fc0000
31747 close(3)                          = 0
31747 open("/usr/lib64/libbfd-2.25.0.so", O_RDONLY|O_CLOEXEC) = 3
31747 read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\200\250\v\0\0\0\0\0"..., 832) = 832

31747 fstat(3, {st_mode=S_IFREG|0755, st_size=3414992, ...}) = 0
31747 mmap(NULL, 5543872, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7fbd4288d000
31747 mprotect(0x7fbd42b5c000, 2097152, PROT_NONE) = 0
31747 mmap(0x7fbd42d5c000, 471040, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x2cf000) = 0x7fbd42d5c000
31747 mmap(0x7fbd42dcf000, 30656, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7fbd42dcf000
31747 close(3)                          = 0
31747 open("/usr/lib64/mpi/gcc/openmpi/lib64/libc.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
31747 open("/lib64/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
31747 read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\360\34\2\0\0\0\0\0"..., 832) = 832
31747 fstat(3, {st_mode=S_IFREG|0755, st_size=2003811, ...}) = 0
31747 mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fbd42fbf000
31747 mmap(NULL, 3856928, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7fbd424df000
31747 mprotect(0x7fbd42683000, 2097152, PROT_NONE) = 0
31747 mmap(0x7fbd42883000, 24576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1a4000) = 0x7fbd42883000
31747 mmap(0x7fbd42889000, 14880, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7fbd42889000
31747 close(3)                          = 0
31747 open("/usr/lib64/mpi/gcc/openmpi/lib64/libz.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
31747 open("/lib64/libz.so.1", O_RDONLY|O_CLOEXEC) = 3
31747 read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\0%\0\0\0\0\0\0"..., 832) = 832
31747 fstat(3, {st_mode=S_IFREG|0755, st_size=88216, ...}) = 0
31747 mmap(NULL, 2183304, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7fbd422c9000
31747 mprotect(0x7fbd422de000, 2093056, PROT_NONE) = 0
31747 mmap(0x7fbd424dd000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x14000) = 0x7fbd424dd000
31747 close(3)                          = 0
31747 open("/usr/lib64/mpi/gcc/openmpi/lib64/libdl.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
31747 open("/lib64/libdl.so.2", O_RDONLY|O_CLOEXEC) = 3
31747 read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\320\16\0\0\0\0\0\0"..., 832) = 832
31747 fstat(3, {st_mode=S_IFREG|0755, st_size=18904, ...}) = 0
31747 mmap(NULL, 2109712, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7fbd420c5000
31747 mprotect(0x7fbd420c8000, 2093056, PROT_NONE) = 0
31747 mmap(0x7fbd422c7000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x2000) = 0x7fbd422c7000
31747 close(3)                          = 0
31747 mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fbd42fbe000
31747 mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fbd42fbd000
31747 mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fbd42fbc000
31747 arch_prctl(ARCH_SET_FS, 0x7fbd42fbd700) = 0
31747 mprotect(0x7fbd42883000, 16384, PROT_READ) = 0
31747 mprotect(0x7fbd422c7000, 4096, PROT_READ) = 0
31747 mprotect(0x7fbd424dd000, 4096, PROT_READ) = 0
31747 mprotect(0x7fbd42d5c000, 405504, PROT_READ) = 0
31747 mprotect(0x605000, 4096, PROT_READ) = 0
31747 mprotect(0x7fbd42ff6000, 4096, PROT_READ) = 0
31747 munmap(0x7fbd42fc0000, 216273)    = 0
31747 brk(0)                            = 0x11b9000
31747 brk(0x11da000)                    = 0x11da000
31747 open("/usr/lib/locale/locale-archive", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
31747 open("/usr/share/locale/locale.alias", O_RDONLY|O_CLOEXEC) = 3
31747 fstat(3, {st_mode=S_IFREG|0644, st_size=2434, ...}) = 0
31747 mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fbd42ff4000
31747 read(3, "# Locale name alias data base.\n#"..., 4096) = 2434
31747 read(3, "", 4096)                 = 0
31747 close(3)                          = 0
31747 munmap(0x7fbd42ff4000, 4096)      = 0
31747 open("/usr/lib/locale/fr_FR.UTF-8/LC_MESSAGES", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
31747 open("/usr/lib/locale/fr_FR.utf8/LC_MESSAGES", O_RDONLY|O_CLOEXEC) = 3
31747 fstat(3, {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
31747 close(3)                          = 0
31747 open("/usr/lib/locale/fr_FR.utf8/LC_MESSAGES/SYS_LC_MESSAGES", O_RDONLY|O_CLOEXEC) = 3
31747 fstat(3, {st_mode=S_IFREG|0644, st_size=54, ...}) = 0
31747 mmap(NULL, 54, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7fbd42ff4000

31747 close(3)                          = 0
31747 open("/usr/lib64/gconv/gconv-modules.cache", O_RDONLY) = 3
31747 fstat(3, {st_mode=S_IFREG|0644, st_size=26244, ...}) = 0
31747 mmap(NULL, 26244, PROT_READ, MAP_SHARED, 3, 0) = 0x7fbd42fed000
31747 close(3)                          = 0
31747 open("/usr/lib/locale/fr_FR.UTF-8/LC_CTYPE", O_RDONLY|O_CLOEXEC) = 
-1 ENOENT (No such file or directory)
31747 open("/usr/lib/locale/fr_FR.utf8/LC_CTYPE", O_RDONLY|O_CLOEXEC) = 3
31747 fstat(3, {st_mode=S_IFREG|0644, st_size=256356, ...}) = 0
31747 mmap(NULL, 256356, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7fbd42f7d000
31747 close(3)                          = 0
31747 stat("/proc/31689/exe", 0x7fff490ca660) = -1 EACCES (Permission 
denied)
31747 open("/usr/share/locale-langpack/fr_FR.UTF-8/LC_MESSAGES/libc.mo", 
O_RDONLY) = -1 ENOENT (No such file or directory)
31747 open("/usr/share/locale/fr_FR.UTF-8/LC_MESSAGES/libc.mo", 
O_RDONLY) = -1 ENOENT (No such file or directory)
31747 open("/usr/share/locale-bundle/fr_FR.UTF-8/LC_MESSAGES/libc.mo", 
O_RDONLY) = -1 ENOENT (No such file or directory)
31747 open("/usr/share/locale-langpack/fr_FR.utf8/LC_MESSAGES/libc.mo", 
O_RDONLY) = -1 ENOENT (No such file or directory)
31747 open("/usr/share/locale/fr_FR.utf8/LC_MESSAGES/libc.mo", O_RDONLY) 
= -1 ENOENT (No such file or directory)
31747 open("/usr/share/locale-bundle/fr_FR.utf8/LC_MESSAGES/libc.mo", 
O_RDONLY) = -1 ENOENT (No such file or directory)
31747 open("/usr/share/locale-langpack/fr_FR/LC_MESSAGES/libc.mo", 
O_RDONLY) = -1 ENOENT (No such file or directory)
31747 open("/usr/share/locale/fr_FR/LC_MESSAGES/libc.mo", O_RDONLY) = -1 
ENOENT (No such file or directory)
31747 open("/usr/share/locale-bundle/fr_FR/LC_MESSAGES/libc.mo", 
O_RDONLY) = -1 ENOENT (No such file or directory)
31747 open("/usr/share/locale-langpack/fr.UTF-8/LC_MESSAGES/libc.mo", 
O_RDONLY) = -1 ENOENT (No such file or directory)
31747 open("/usr/share/locale/fr.UTF-8/LC_MESSAGES/libc.mo", O_RDONLY) = 
-1 ENOENT (No such file or directory)
31747 open("/usr/share/locale-bundle/fr.UTF-8/LC_MESSAGES/libc.mo", 
O_RDONLY) = -1 ENOENT (No such file or directory)
31747 open("/usr/share/locale-langpack/fr.utf8/LC_MESSAGES/libc.mo", 
O_RDONLY) = -1 ENOENT (No such file or directory)
31747 open("/usr/share/locale/fr.utf8/LC_MESSAGES/libc.mo", O_RDONLY) = 
-1 ENOENT (No such file or directory)
31747 open("/usr/share/locale-bundle/fr.utf8/LC_MESSAGES/libc.mo", 
O_RDONLY) = -1 ENOENT (No such file or directory)
31747 open("/usr/share/locale-langpack/fr/LC_MESSAGES/libc.mo", 
O_RDONLY) = -1 ENOENT (No such file or directory)
31747 open("/usr/share/locale/fr/LC_MESSAGES/libc.mo", O_RDONLY) = 3
31747 fstat(3, {st_mode=S_IFREG|0644, st_size=153231, ...}) = 0
31747 mmap(NULL, 153231, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7fbd42fc7000
31747 close(3)                          = 0
31747 
open("/usr/share/locale-langpack/fr_FR.UTF-8/LC_MESSAGES/binutils.mo", 
O_RDONLY) = -1 ENOENT (No such file or directory)
31747 open("/usr/share/locale/fr_FR.UTF-8/LC_MESSAGES/binutils.mo", 
O_RDONLY) = -1 ENOENT (No such file or directory)
31747 
open("/usr/share/locale-bundle/fr_FR.UTF-8/LC_MESSAGES/binutils.mo", 
O_RDONLY) = -1 ENOENT (No such file or directory)
31747 
open("/usr/share/locale-langpack/fr_FR.utf8/LC_MESSAGES/binutils.mo", 
O_RDONLY) = -1 ENOENT (No such file or directory)
31747 open("/usr/share/locale/fr_FR.utf8/LC_MESSAGES/binutils.mo", 
O_RDONLY) = -1 ENOENT (No such file or directory)
31747 
open("/usr/share/locale-bundle/fr_FR.utf8/LC_MESSAGES/binutils.mo", 
O_RDONLY) = -1 ENOENT (No such file or directory)
31747 open("/usr/share/locale-langpack/fr_FR/LC_MESSAGES/binutils.mo", 
O_RDONLY) = -1 ENOENT (No such file or directory)
31747 open("/usr/share/locale/fr_FR/LC_MESSAGES/binutils.mo", O_RDONLY) 
= -1 ENOENT (No such file or directory)
31747 open("/usr/share/locale-bundle/fr_FR/LC_MESSAGES/binutils.mo", 
O_RDONLY) = -1 ENOENT (No such file or directory)
31747 
open("/usr/share/locale-langpack/fr.UTF-8/LC_MESSAGES/binutils.mo", 
O_RDONLY) = -1 ENOENT (No such file or directory)
31747 open("/usr/share/locale/fr.UTF-8/LC_MESSAGES/binutils.mo", 
O_RDONLY) = -1 ENOENT (No such file or directory)
31747 open("/usr/share/locale-bundle/fr.UTF-8/LC_MESSAGES/binutils.mo", 
O_RDONLY) = -1 ENOENT (No such file or directory)
31747 open("/usr/share/locale-langpack/fr.utf8/LC_MESSAGES/binutils.mo", 
O_RDONLY) = -1 ENOENT (No such file or directory)
31747 open("/usr/share/locale/fr.utf8/LC_MESSAGES/binutils.mo", 
O_RDONLY) = -1 ENOENT (No such file or directory)
31747 open("/usr/share/locale-bundle/fr.utf8/LC_MESSAGES/binutils.mo", 
O_RDONLY) = -1 ENOENT (No such file or directory)
31747 open("/usr/share/locale-langpack/fr/LC_MESSAGES/binutils.mo", 
O_RDONLY) = -1 ENOENT (No such file or directory)
31747 open("/usr/share/locale/fr/LC_MESSAGES/binutils.mo", O_RDONLY) = 3
31747 fstat(3, {st_mode=S_IFREG|0644, st_size=217397, ...}) = 0
31747 mmap(NULL, 217397, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7fbd42f47000
31747 close(3)                          = 0
31689 +++ killed by SIGABRT +++
31747 write(2, "addr2line: ", 11)       = -1 EPIPE (Broken pipe)
31747 --- SIGPIPE {si_signo=SIGPIPE, si_code=SI_USER, si_pid=31747, 
si_uid=3204} ---
31747 write(2, "Attention\302\240: ne peut localiser \302"..., 90) = -1 
EPIPE (Broken pipe)
31747 --- SIGPIPE {si_signo=SIGPIPE, si_code=SI_USER, si_pid=31747, 
si_uid=3204} ---
31747 write(2, "\n", 1)                 = -1 EPIPE (Broken pipe)
31747 --- SIGPIPE {si_signo=SIGPIPE, si_code=SI_USER, si_pid=31747, 
si_uid=3204} ---
31747 exit_group(1)                     = ?
31747 +++ exited with 1 +++

**Comment by rgleason** [comment]
Gshhs  High Res 
http://opencpn.org/ocpn/chart_sources
http://www.idlcoyote.com/map_tips/gshhs.html

Sean has it changed to gshhg ??
https://www.ngdc.noaa.gov/mgg/shorelines/gshhs.html
"GSHHG combines the older GSHHS shoreline database with WDBII rivers and borders,"

**Comment by nohal** [comment]
Dominig...
The basemap data prepared for packaging is at http://sourceforge.net/projects/opencpnplugins/files/opencpn_packaging_data/opencpn-gshhs_2.2.4.tar.xz/download
In the DEB packages, we have them packaged in 5 different resolutions: opencpn-gshhs-crude, opencpn-gshhs-low, opencpn-gshhs-intermediate, opencpn-gshhs-high, opencpn-gshhs-full
The crude resolution is also included in the main code repository, but is not installed/packaged with the program by default on Linux - see https://github.com/OpenCPN/OpenCPN/pull/151 for details

Pavel 


Pavel

**Comment by dominig** [comment]
adding the gshhs file is high definition fix the issue.
I let you close the issue.
My advise you be to issue to clear error message when the required data are not present.
In OpenSUSE, I have now added a dependency to a gshhs-data package what will hide the issue for the standard user.
Thanks for the help

**Comment by seandepagnier** [comment]
We didn't fix the problem yet did we?   I want to be clear.. if you remove gshhs completely and try to use weather routing then the program crashes but doesn't crash in any other case?  Or can it crash with a lower detail level?

Perhaps the weather routing plugin should detect which gshhs detail level is installed and advise the user if it is not the highest resolution?   I still have a plan to use cm93 contours eventually as well.

**Comment by dominig** [comment]
Hello,
    
    no the problem is not corrected but loading the high definition of
    gshhs files hides it.
    It's a work around.
    Dominig ar Foll
Senior Software Architect
Open Source Technology Centre
Intel SSG
    Le 23/06/2015 12:21, seandepagnier a
      écrit :
    
    
      We didn't fix the problem yet did we? I want to be clear.. if
        you remove gshhs completely and try to use weather routing then
        the program crashes but doesn't crash in any other case? Or can
        it crash with a lower detail level?
      Perhaps the weather routing plugin should detect which gshhs
        detail level is installed and advise the user if it is not the
        highest resolution? I still have a plan to use cm93 contours
        eventually as well.
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by rgleason** [comment]
Sean did this get fixed?
If so, you can close it.

**Comment by rgleason** [comment]
SEan, can you close this?  I can't and it is fixed.

**Comment by dominig** [comment]
As I have created it I can close it.
Thanks.

Dominig
