### ISSUE TITLE
FS#1778 - compiling when FGrib plugin is notopen crashes OpenCPN. 

### ISSUE THREAD

**Issue by dominig** [seandepagnier/weather_routing_pi#18]
Apoliogies for the dual post.

 FS#1778 - compiling when FGrib plugin is notopen crashes OpenCPN.

-------------------------------------------
Version:
OpenCPN
Stable 4.0
Weather routing Plugin
SHA 9a19a5aa45b3eabe70ebf47798392bc8cc300e9f
date 10 May 2015

Start Weather routing
Create start and points
Hit Configuration > New
Leave all the default option
Close configuration window.
Hit Configuration > Compile
compilation slider open and progress until the end
OpenCPN crashes

Message on console
*** opencpn (wxWidgets 2.8.12) crashed ***, see backtrace!
[xcb] Unknown request in queue while dequeuing
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
opencpn: xcb_io.c�:179�:�dequeue_pending_request: l'assertion ��!xcb_xlib_unknown_req_in_deq�� a �chou�.
Abandon

OpenCPN log has no extra info.

**Comment by rgleason** [comment]
Doming, Do you set the time to "Grib Time" ?

**Comment by dominig** [comment]
Hello,

since updated a few plugins to correct many small issue that specific bug cannot be reproduced anymore.

Dominig

**Comment by rgleason** [comment]
Sean, This can be closed. (Dominig and I cant close it.)

**Comment by rgleason** [comment]
Sean,
You are the one who might be able to close this, I can't and Domming doesn't close it but agrees.

**Comment by dominig** [comment]
It seems that I can close it time :-)
