### ISSUE TITLE
Edit Polar File in Dim Tab - Add two TWS-columns - Save - then Save Boat - O Failure

### ISSUE THREAD

**Issue by rgleason** [seandepagnier/weather_routing_pi#180]
See the end of #170 (closed) for more details and screen shots.  It's a Mystery.
Fortunately the changes to the polar file are saved successfully and available after restarting Opencpn and WxRte again.   So is this 1/2 a bug?  

This does not happen on Stelian's virtual machine, but it does happen on my two machines.

Two jelly beans to anyone who solves this.

**Comment by stelian42** [comment]
And you know what ? I've just reproduced the problem... on Linux !

It's the same "paint" issue I believed I fixed yesterday.

See the backtrace:
Thread 1 "opencpn" received signal SIGINT, Interrupt.
0x00007fffcd69fcc0 in positive_degrees (degrees=4.9829647068482765e+18) at /home/stelian/TMP/ocpn_pi/weather_routing_pi_stelian.git/src/Utilities.cpp:55
55	    while(degrees >= 360)
(gdb) bt
#0  0x00007fffcd69fcc0 in positive_degrees(double) (degrees=4.9829647068482765e+18) at /home/stelian/TMP/ocpn_pi/weather_routing_pi_stelian.git/src/Utilities.cpp:55
#1  0x00007fffcd67baf2 in Polar::Speed(double, double, bool, bool) (this=0x55555eb68630, W=4.9829647068482765e+18, VW=15, bound=false, optimize_tacking=false)
    at /home/stelian/TMP/ocpn_pi/weather_routing_pi_stelian.git/src/Polar.cpp:480
#2  0x00007fffcd65fb37 in BoatDialog::OnPaintPlot(wxPaintEvent&) (this=0x55555e8a4930, event=...)
    at /home/stelian/TMP/ocpn_pi/weather_routing_pi_stelian.git/src/BoatDialog.cpp:449
#3  0x00007ffff523a7ee in wxEvtHandler::ProcessEventIfMatchesId(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&) () at /usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#4  0x00007ffff523abfa in wxEvtHandler::SearchDynamicEventTable(wxEvent&) () at /usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#5  0x00007ffff523ac8f in wxEvtHandler::TryHereOnly(wxEvent&) () at /usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#6  0x00007ffff523ad43 in wxEvtHandler::ProcessEventLocally(wxEvent&) () at /usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#7  0x00007ffff523ada5 in wxEvtHandler::ProcessEvent(wxEvent&) () at /usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#8  0x00007ffff5988bfd in wxScrollHelperEvtHandler::ProcessEvent(wxEvent&) () at /usr/lib/x86_64-linux-gnu/libwx_gtk2u_core-3.0.so.0
#9  0x00007ffff523ab07 in wxEvtHandler::SafelyProcessEvent(wxEvent&) () at /usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#10 0x00007ffff576b257 in wxWindow::GTKSendPaintEvents(_GdkRegion const*) () at /usr/lib/x86_64-linux-gnu/libwx_gtk2u_core-3.0.so.0
#11 0x00007ffff576ba24 in  () at /usr/lib/x86_64-linux-gnu/libwx_gtk2u_core-3.0.so.0
#12 0x00007fffedd9cb7b in  () at /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#13 0x00007ffff76eff9d in g_closure_invoke () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#14 0x00007ffff7702cde in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#15 0x00007ffff770ae4f in g_signal_emit_valist () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#16 0x00007ffff770becf in g_signal_emit () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#17 0x00007fffedeb2f9c in  () at /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#18 0x00007fffedd9b958 in gtk_main_do_event () at /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#19 0x00007ffff6d00b9f in  () at /usr/lib/x86_64-linux-gnu/libgdk-x11-2.0.so.0
#20 0x00007ffff6d00b45 in  () at /usr/lib/x86_64-linux-gnu/libgdk-x11-2.0.so.0
#21 0x00007ffff6d00b45 in  () at /usr/lib/x86_64-linux-gnu/libgdk-x11-2.0.so.0
#22 0x00007ffff6d00b45 in  () at /usr/lib/x86_64-linux-gnu/libgdk-x11-2.0.so.0
#23 0x00007ffff6d00b45 in  () at /usr/lib/x86_64-linux-gnu/libgdk-x11-2.0.so.0
#24 0x00007ffff6d00b45 in  () at /usr/lib/x86_64-linux-gnu/libgdk-x11-2.0.so.0
#25 0x00007ffff6cfd623 in  () at /usr/lib/x86_64-linux-gnu/libgdk-x11-2.0.so.0
#26 0x00007ffff6cfdfb0 in gdk_window_process_all_updates () at /usr/lib/x86_64-linux-gnu/libgdk-x11-2.0.so.0
#27 0x00007ffff6cfdff9 in  () at /usr/lib/x86_64-linux-gnu/libgdk-x11-2.0.so.0
#28 0x00007ffff6cdcc1c in  () at /usr/lib/x86_64-linux-gnu/libgdk-x11-2.0.so.0
#29 0x00007ffff1132e25 in g_main_context_dispatch () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#30 0x00007ffff11331f0 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#31 0x00007ffff1133502 in g_main_loop_run () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#32 0x00007fffedd9a727 in gtk_main () at /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#33 0x00007ffff5743905 in wxGUIEventLoop::DoRun() () at /usr/lib/x86_64-linux-gnu/libwx_gtk2u_core-3.0.so.0
#34 0x00007ffff50f6a73 in wxEventLoopBase::Run() () at /usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#35 0x00007ffff50bdf96 in wxAppConsoleBase::MainLoop() () at /usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#36 0x00007ffff5148d69 in wxEntry(int&, wchar_t**) () at /usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#37 0x00005555556fee98 in main(int, char**) (argc=<optimized out>, argv=<optimized out>) at /home/stelian/TMP/OpenCPN_stelian.git/src/chart1.cpp:921

**Comment by rgleason** [comment]
You're awesome!  What kind of jelly beans do you like?

**Comment by stelian42** [comment]
I'll tell you that if I succeed in fixing it !

**Comment by stelian42** [comment]
Rick, please test the automated build from #182 and tell me what you think !
