### ISSUE TITLE
Detect Boundary problem

### ISSUE THREAD

**Issue by rgleason** [seandepagnier/weather_routing_pi#191]
See attached photo please.  "Failed to start configuration. Configuration specifies Boundary Exclusion, but opencpn boundary information not available."

This occurs for Bounndaries that are Exclusion, Inclusion or Neither.

I believe that the message format may have changed in Ocpn_Draw, (although I cannot find the commit for that in Ocpn_draw)  OR the many changes/improvements to ocpn_draw affected messaging within that plugin.

See these notes which should be updated: https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:developer_manual:developer_guide:messaging

Here is the ocpn_plugin.h https://github.com/OpenCPN/OpenCPN/blob/623d6a95918d7c7bec450e521190c6b415858e15/include/ocpn_plugin.h

![screenshot 63](https://user-images.githubusercontent.com/2363959/39364870-6d52b7de-49fd-11e8-9c46-14c138963baa.png)

I've tried to find the record in the API but can't..

**Comment by jongough** [comment]
Rick,
   What versions of the plugins are you using? Also, I always have problems with the polar files and it takes me quite a while to even get the weather routing plugin to get past that. Any hints as to what I have to do to try it out?

Thanks
Jon

**Comment by jongough** [comment]
Hi Rick,
   I have it sort of working, but it does not draw the route for me (maybe my version of WR (1.10) is too old). This version is using the ODAPI and looking for any boundary in any state to see if the route will cross it. The ODAPI seems to be working OK. 

Regards
   Jon

**Comment by jongough** [comment]
Hi Rick,
   Just installed the new version of WD (1.12.0 - 2018-03-25) and it works with boundaries OK, sort of. If I put a boundary in the way it routes round it, but if I block off a channel it seems to have issues with land areas. Also, the new version is using the JSON messaging rather than the ODAPI, which is a bit surprising as I added the API especially for this sort of thing.

**Comment by rgleason** [comment]
Jon, Sean and Dig-g have been hard a work on Wxrouting and there are frequent updates. I think Did-g is trying to make Wxroute complete the computation in tight situations with intervals that are too big for the situation. He also seems to be fixing some code issues and I don't know weather the anatomies were always there or have arisen due to some of these changes. 

First, I think it would be best to confirm that the API messaging is working properly in both Watchdog and Weather-Routing.  Fix those problems if any.

Then it would be nice to identify a pattern for  when wxrouting  it does not detect land or boundaries. 
Also see  
https://github.com/seandepagnier/weather_routing_pi/issues/196#issue-318450293
https://github.com/seandepagnier/weather_routing_pi/issues/195
https://github.com/seandepagnier/weather_routing_pi/issues/191
(For some reason the detect boundary issue went away)  I am somewhat in the dark as to why! 
I toggled the Boundary properties for Exclusion, Inclusion, neither, and also active/inactive.

Is there some way I can help with testing the messaging?

I am sorry but I don't understand the differences betweeen ODAPI and JSON messaging. Are there two channels for messages or something?

I am going to try workiing with Watchdog now too.

**Comment by rgleason** [comment]
Well making a new Boundary in Ocpn_Draw around Nassau and re running the wxroute, the boundary seems to be recognized now and wxroute routes right around Nassau now.  (However, the detect land isn't working right yet!)

![screenshot 70](https://user-images.githubusercontent.com/2363959/39396839-d64eee1c-4ac3-11e8-8d60-cfb2a3646d57.png)

**Comment by nohal** [comment]
Are you sure you use the full resolution GSHHG data?

**Comment by rgleason** [comment]
Yes, right again. I realize you must download Opencpn GSHHG each time you install a new parallel install becuase it is located in the program x86 path under opencpn/gshhg, unlike a chart.

**Comment by jongough** [comment]
Hi Rick,
   There are two methods of interacting with OD programatically, OCPN messaging using JSON messages and the ODAPI. Basically the OCPN messaging is synchronous and broadcast, so every plugin gets the message being sent and the originator is blocked until the message process completes. Also, the message is in JSON format which requires decoding, so every plugin that is registered for messaging has to decode the message to see if it is interested in it. The ODAPI uses the messaging process to give out the real address of the API, but once this is done it is possible to call the available OD functions directly with a C structure.

   So the OCPN JSON message is useful for letting multiple plugins know what is going on and for low message rate processes. For targeted, high rate, message/communitaions it is not really usable in its current format (Dave said he was going to look into it for OCPN V5). For Watchdog and Weather Routing the message rate can be high and it is only for OD, no one else should be interested in the messages, so the ODAPI was created to avoid the JSON overhead and to allow plugins to communicate directly with OD (in fact execute OD code as it was part of their plugin).

    The original ODAPI only had three functions which were read only, i.e. check if a boundary is crossed , but with OD 1.5 I am now increasing this to 5 or 6 and allowing objects to be created, i.e. new boundaries, boundary points and text points. This means that creating boundaries programatically, which I think Didier is doing by a hack, will be possible. It will also allow Text Points to be used for storing anchorage information which is currently done in waypoints.

Regards
   Jon

**Comment by rgleason** [comment]
Great Pavel. Thanks, will do so.
"Not true with the current versions of OpenCPN. Simply have one GSHHG folder and add it as a normal chart directory to all the instances, like a chart."

Jon, thank you for the explanation. Very helpful.

**Comment by rgleason** [comment]
I am going to keep this open until I can copy Jon's commentary to ocpn_draw api page.
