### ISSUE TITLE
Bug in gshhs landcrossing test

### ISSUE THREAD

**Issue by did-g** [seandepagnier/weather_routing_pi#199]
It thinks 
p *it2
$60 = (wxLineF &) @0xaf605e68: {m_p1 = {x = 358,388667, y = 49,649971999999998}, m_p2 = {x = 358,388667, y = 49,648305999999998}}
(gdb) p rtrajectWorld
$61 = {m_p1 = {x = 358,40960200000001, y = 49,676139999999997}, m_p2 = {x = 358,409605, y = 49,771659}}

intersect

**Comment by seandepagnier** [comment]
it's not a weather routing bug, but yes, vertical line segments apparently computed wrong.. try this:

[gshhs_fix.diff.txt](https://github.com/seandepagnier/weather_routing_pi/files/2011321/gshhs_fix.diff.txt)

**Comment by did-g** [comment]
Hi,
Yes it's not in weather routing but AFAIK WR and Watchdog are the main users of it.
Patch seems to work , my_intersects could be declared static though.

Regards
Didier

**Comment by rgleason** [comment]
Should this be close now or not?  It would be Sean or Did-g to close.  I cannot do it.
