### ISSUE TITLE
Routings with Climatology - missing voyage data

### ISSUE THREAD

**Issue by rgleason** [seandepagnier/weather_routing_pi#201]
The routings with climatology only seem to be missing voyage data, such as duration, time of start and finish....
If we are using a specific date and time for the start, why is this happening?

For Example

![ct-azores-climatology](https://user-images.githubusercontent.com/2363959/40735954-9969a982-640a-11e8-8f33-546d0abfbb2d.png)
![ct-azores-noaa-grib](https://user-images.githubusercontent.com/2363959/40735957-9e586136-640a-11e8-95a7-ea41c5b7b079.png)

**Comment by did-g** [comment]
Hi,
I can't tell from your screens capture but my guess is that it can't reach destination.

Huh? Yep,  routing ends if destination is inside two isochrons, what you have, but remember between these two isochrons boat can only moves in straight lines and if there's land in the way destination could be unreachable. Islands are prone to this kind of issue.

**Comment by rgleason** [comment]
Ah ha. I really should have known that!  I located the WP end point inside Horta Harbor.
I had similar issues coming out of Stonington CT and relocated the start point out by Block Island.

It would be very nice to have a secondary Start/End Interval setting that could be user set (like 1/10 of the main interval)  with a user duration (like 5x the primary interval)

It would be even better to have these settings adaptable to the start and end conditions.

**Comment by rgleason** [comment]
Closing.  See https://github.com/seandepagnier/weather_routing_pi/issues/202

**Comment by did-g** [comment]
Hi
It would be better if user woudn't have to babysit the computer. 

You can try something like that with my O version:
-first 5 loops use a small time interval and search on 360,
-try to reduce time interval when end is near. This one doesn't work well it slows search a lot.
Both don't always work. Best would be backtracking on error with a smaller time step.

https://ci.appveyor.com/api/buildjobs/57rqkjlyuyhp70qn/artifacts/build%2Fopencpn_5.1.10601_setup.exe
100 % incompatible with stock OCPN but it installs all plugins  in the same exe.

**Comment by rgleason** [comment]
Thank did-g I'll install it.  I see you've been thinking about this problem!

**Comment by seandepagnier** [comment]
It's not an easy problem to solve in a way that will work well in all cases.

I am interested in experiments.. it would be helpful feedback for
writing a new more efficient routing algorithm.  If it could use the
graphics hardware (gpu) that would be interesting as well.

**Comment by rgleason** [comment]
Right now the finer grain settings might be good for wide open ocean direct to a harbor. The coastal zone with landforms can vary in width from 1nm to 30 nm.  There are also situations where the optimal routing will run into mid voyage coastal zones  (of varying widths), so this case does not just occur at the start and end.  

Is there a decent way to detect coastal zones?  If so, perhaps there should be a Coastal zone detection checkbox?   Maybe the gshhg can be used to provide a coastal zone complexity factor and coastal zone width distance.  Those could be used to automatically fine tune the time interval so that it is fine enough to complete, but not so detailed that it slows the calculations too much.

I think the problem with doing this is that it starts to become calculation intensive, but you guys have a better sense of this.

I am going to attach a few shots from using dig-g's version.  I was able to move the start point almost back towards where it originally failed and set the interval to 2 hours, and the routing completed. The issue I see is that the secondary interval might be good for  leaving  harbor  ---> ocean, but not for wider coastal zones, say 16-20 nm where there is a reasonable chance that computation will fail.
--Maybe a  range of time intervals is needed depending on the scale and complexity of the landforms?

![screenshot 172](https://user-images.githubusercontent.com/2363959/40874664-069c9eba-6640-11e8-873b-cb959919ebf2.png)
![screenshot 173](https://user-images.githubusercontent.com/2363959/40874667-0cc0bb3c-6640-11e8-9a87-a93181606f10.png)
![screenshot 174](https://user-images.githubusercontent.com/2363959/40874670-153b92dc-6640-11e8-832d-23596c2847b6.png)

**Comment by rgleason** [comment]
So why is this happening polar:land:failed?
I have max diverted=110  and also have set Advanced Max search angle=150
but it does not seem to want to go SE below Block Island. It should find that route I think.
![screenshot 180](https://user-images.githubusercontent.com/2363959/40874929-feee28e6-6644-11e8-9b38-e0e0a1818a2e.png)
![screenshot 181](https://user-images.githubusercontent.com/2363959/40874930-03c3d226-6645-11e8-857f-47e736042dfb.png)

**Comment by rgleason** [comment]
Now I think I know what the problem was, the Polar only goes to 20 knts. so it routed up to the NE.

**Comment by did-g** [comment]
Hi,
With my version the best is to use half your wind data time interval and 5 to 10° angular step. Routing is automagically trying to reduce time interval on start/end steps and it reduces angular step if hitting somethings. But it still fails too many times.

Moreover with this version you can:
- Use O waypoints, if WR dialog is open  there's  a new entry in waypoint's contextual menu, moving the waypoint with the mouse update WR position.
- Add an O route to WR for computing weather along it.

-  Download GFS grib from O grib mail dialog both GFS +HRR from NOAA and french data from me. 
- Update saildocs
- NOAA HRRR is Lambert conformal so data are partially wrong, not rotated for UV and lat/long to x/y doesn't work, moreover pressure is surface not MSL so on land it's worthless, at least it helps double checking x/y to lat/lon is not too bad, isobars neatly overlapping land.

- With draw you can generate boundary from S57 and oesenc charts (oesenc only on linux, I think I don't properly compile it on window and it crashes ). on DR dialog box there's a new button, beware it's slow.
