### ISSUE TITLE
Routing in 0-2 knot wind  - Failures

### ISSUE THREAD

**Issue by rgleason** [seandepagnier/weather_routing_pi#213]
The entire routing fails.  I had to enter wind columns for 1 and 2 and then some low values and the routing worked.

**Comment by rgleason** [comment]
Maybe I should be putting  0.1 in those columns, so that the boat just stays in one place and the routing will complete?

**Comment by rgleason** [comment]
Actually you can make a  TWS=1  and TWS=2 column and put  0.1 in the upper and lower angles, to just hold position, then the routing works.  The User really should have a separate polar for lower wind speeds and add that to the boat file.

**Comment by JonathanHuot** [comment]
Workaround works for me.
