### ISSUE TITLE
Boat info for polar are only in imperial

### ISSUE THREAD

**Issue by dominig** [seandepagnier/weather_routing_pi#22]
For people leaving in metrics countries, feet are only used at best for the branding of their boar all technical infos are in Meters.
In OpenCPN option, there is no general preference for metric or Imperial (it would be nice) but at least I would expect to be able to select Metrics units somewhere in the polar info menu.

Thanks.

Dominig

**Comment by rgleason** [comment]
Dear Dominig,
Our boar are pretty much gone but we still use feet. However you make a very good point. There is no universal place to set units that are used in plugins. It would first have to be put into the plugin api and opencpn. Then each plugin author would have to impliment.
If you would make this a feature request in Tracker that would be very much appreciated.

**Comment by seandepagnier** [comment]
It doesn't actually affect the routing if you load the polar from a
file, only if the polar is computed.

**Comment by dominig** [comment]
Feature request created.
 FS#1852 - No generic entry to pass the information for plugins for which units to use.

**Comment by rgleason** [comment]
Good, Dominig you should also vote for it. I also voted. Thanks.

**Comment by seandepagnier** [comment]
I no longer use boat parameters, but in the future I will try to have metrics when I do.
