### ISSUE TITLE
clicking twice on compute can kill opencpn

### ISSUE THREAD

**Issue by did-g** [seandepagnier/weather_routing_pi#229]
Hi,
- Create  a route configuration with climatology only
- Click Compute
- while Climatology loading dialog is open click Compute again
==> SIGSEV because climatology data aren't there yet.

Not sure the proper and safer way to fix it.

**Comment by seandepagnier** [comment]
For now can we assume user eventually learns not to do this?  I'm open to a real fix but the user can already avoid this.

**Comment by rgleason** [comment]
Did-g  Is this fixed?  I tried to do this but it did not crash.

**Comment by did-g** [comment]
No, it's still there on linux.

**Comment by rgleason** [comment]
Great, I guess this is fixed now. So we can close it. I am not able to close it. I has to be Sean or Didier.
