### ISSUE TITLE
French translation for Sail Area

### ISSUE THREAD

**Issue by dominig** [seandepagnier/weather_routing_pi#23]
Hello,

In boat configuration for the Polar calculation, I am not able to understand 'Zone de Navigation', when I look at the french translation file po/fr.po I see the English 'Sail Area'.

#: src/WeatherRoutingUI.cpp:1548
msgid "Sail Area"
msgstr "Zone de navigation"

I am not sure that what you mean is the actual area of the sail (in that case which sail ?). As I gave not found any info on this entry in your documentation web page, I cannot yet propose a beter translation.
But if you let me know what is hidden behind that entry, I will provide you with a correct translation.

regards

Dominig

**Comment by rgleason** [comment]
Under Weather_Routing > Configuration [Select a config] > Edit > Under "Boat" select "Edit" >  Tab "Boat Configuration" is a list of Boat Characteristics  one of them being listed as "Sale Area" which is supposed to be in units of "square feet".  A metric converter is useful.  1 sq meter = 10.76 sq ft. http://www.thecalculatorsite.com/conversions/area.php
It might be helpful to have the po show the conversion factor if possible.

**Comment by seandepagnier** [comment]
As far as translations go, we are using crowdin
https://crowdin.com/project/opencpn so you can make corrections there.

**Comment by rgleason** [comment]
Darn, correction needed. "Sail Area". Spell check????

**Comment by dominig** [comment]
I am happy to push a correction, but I would be sure to understand what is meant by Sail Area in polar calculation. I would guess full main sail + Genoa  (typical sail surface when Reaching)

**Comment by seandepagnier** [comment]
Sail Area is the total area of all the sails usually in square meters

**Comment by dominig** [comment]
The translation has been corrected 8 months ago at
https://crowdin.com/translate/opencpn/126/en-fr#q=sail
It should show "Surface de voile"

**Comment by seandepagnier** [comment]
I don't understand because it also says the same thing in the fr.po
file I have in github.

The translations were updated June 4

**Comment by dominig** [comment]
9h oder

**Comment by rgleason** [comment]
Sean, Under  Configuration > Edit Boat > Boat Configuration
[Total] "Sail Area"   _____  "sq/ft"    (Square Feet)  (Multiply sq meters x 10.76= sf)
"Length of Water LIne (LWL)" ___ "ft" (Feet)
"Length Overall (LOA) ____ "ft" (Feet)
"Beam"    ___ "ft" (Feet)

Therefore I believe the unit being used is Feet, not Meters.
-It would be very nice to have all plugins recognize the units set in the main program, but the API would need extension to do this I believe, then each plugin would have to use the new extensions.

**Comment by rgleason** [comment]
[Total] "Sail Area" _____ "sq.ft." <-- unit designation should be changed to square feet ?

(Square Feet) (sq ft=10.76 * sm)
