### ISSUE TITLE
Build Compile Errors missing zlib.h

### ISSUE THREAD

**Issue by rgleason** [seandepagnier/weather_routing_pi#238]
Build failiure for windows after git pull of Sean's repository.
> Build FAILED.
> 
> "C:\Users\Frederick\Documents\GitHub\weather_routing_pi\build\ALL_BUILD.vcxproj
> " (default target) (1) ->
> "C:\Users\Frederick\Documents\GitHub\weather_routing_pi\build\weather_routing_p
> i.vcxproj" (default target) (4) ->
> (ClCompile target) ->
>   C:\Users\Frederick\Documents\GitHub\weather_routing_pi\src\SettingsDialog.cpp
> (140): warning C4800: 'long' : forcing value to bool 'true' or 'false' (perform
> ance warning) [C:\Users\Frederick\Documents\GitHub\weather_routing_pi\build\wea
> ther_routing_pi.vcxproj]
>   C:\Users\Frederick\Documents\GitHub\weather_routing_pi\src\BoatDialog.cpp(103
> 6): warning C4800: 'int' : forcing value to bool 'true' or 'false' (performance
>  warning) [C:\Users\Frederick\Documents\GitHub\weather_routing_pi\build\weather
> _routing_pi.vcxproj]
>   C:\Users\Frederick\Documents\GitHub\weather_routing_pi\src\Boat.cpp(267): war
> ning C4305: 'argument' : truncation from 'double' to 'float' [C:\Users\Frederic
> k\Documents\GitHub\weather_routing_pi\build\weather_routing_pi.vcxproj]
>   C:\Users\Frederick\Documents\GitHub\weather_routing_pi\src\RouteMapOverlay.cp
> p(1235): warning C4056: overflow in floating-point constant arithmetic [C:\User
> s\Frederick\Documents\GitHub\weather_routing_pi\build\weather_routing_pi.vcxpro
> j]
>   C:\Users\Frederick\Documents\GitHub\weather_routing_pi\src\LineBufferOverlay.
> cpp(161): warning C4305: 'initializing' : truncation from 'double' to 'float' [
> C:\Users\Frederick\Documents\GitHub\weather_routing_pi\build\weather_routing_pi
> .vcxproj]
> 
> 
> "C:\Users\Frederick\Documents\GitHub\weather_routing_pi\build\ALL_BUILD.vcxproj
> " (default target) (1) ->
> "C:\Users\Frederick\Documents\GitHub\weather_routing_pi\build\weather_routing_p
> i.vcxproj" (default target) (4) ->
> (ClCompile target) ->
>   c:\users\frederick\documents\github\weather_routing_pi\src\zuFile.h(33): fata
> l error C1083: Cannot open include file: 'zlib.h': No such file or directory [C
> :\Users\Frederick\Documents\GitHub\weather_routing_pi\build\weather_routing_pi.
> vcxproj]
>   c:\users\frederick\documents\github\weather_routing_pi\src\zuFile.h(33): fata
> l error C1083: Cannot open include file: 'zlib.h': No such file or directory [C
> :\Users\Frederick\Documents\GitHub\weather_routing_pi\build\weather_routing_pi.
> vcxproj]
> 
>     5 Warning(s)
>     2 Error(s)

**Comment by rgleason** [comment]
Wx-Routing_pi is using wxwidgets 3.1.2 now.  Closing.

**Comment by Hakansv** [comment]
Rick..
Yes, and until needed files are included in the repository or mentioned in the readme you've to copy all zlib....binaries from opencpn\buildwin to \weather_routing_pi\buildwin. (Or from the latest OpenCPN_buildwin-4.99.7z)
