### ISSUE TITLE
ov50 - Bug - wx-Routing requires Climatology_pi installed to be able to disable Climatology use.

### ISSUE THREAD

**Issue by rgleason** [seandepagnier/weather_routing_pi#241]
Presently it is required that Climatology be installed in order to disable the use of Climatology.
IE: If  in Weather-Routing,  Climatology = "Most Likely" has been set, and Climatology is not installed at all, this selection is frozen and causes any "Compute" to fail. 

Workaround Resolution: To turn off  "Most Likely" you must install Climatology, or modify the weatherroutingconfig file manually.   This is a bug.

Solutions: 

1. Allow us to turn off Climatology manually.
2. Allow the compute to run, but have a message that says "Climatology is not loaded"
3. If a compute is hit and Climatology has not been installed  and is enabled, have a message that comes up. Climatology is not installed and it has been enabled.
4. When Wx-routing is loaded without Climatology being on, automatically tun climatology off?

**Comment by dominig** [comment]
Not only it must be installed, it must be enabled and open, to be allowed to deactivate it in Weather routing

**Comment by rgleason** [comment]
Didier has fixed this. Thank you Didier!
