### ISSUE TITLE
Route calculation fails with V 5.0 on Linux OpenSUSE

### ISSUE THREAD

**Issue by dominig** [seandepagnier/weather_routing_pi#245]
Route calculation fails with V 5.0 on Linux OpenSUSE.
I create a route from Sub Belle Ile -> Gijon in Spain.
I download the grib for 10 days (requires far less time).
Use Bavaria 32 polar and Swan 60 which are know to work under 4.8
Start the calculation
Error Grib Fail.
Where can I find some debug info ?
![Screenshot_20190424_221442](https://user-images.githubusercontent.com/1193120/56691017-23732680-66df-11e9-999f-8883c790c08d.png)

(log is empty).
See screen-shot.

**Comment by dominig** [comment]
Changed the tag to route2 on dig branch and the problem has gone.
Nervertheless, it would be nice to have some debug/help to understand what goes wrong when it does fail to compile the route.

**Comment by rgleason** [comment]
Dominig, I am not following this problem very well. Which tag is it?
Also why do you think changing the name helped?
Should this be an Issue?

**Comment by dominig** [comment]
Correct Tagging is often an issue as it's not clear which branch/tag to follow to get the latest small fixes rather than new features.
Having a 5.0 branch tagged (as done in some other plugin would help).
Often packagers needs to do small fixes and those are reintegrated suite slowly what force us to use forks to get the code running.
Using CI (as many packager) our build follows git easily but cannot guess what branch/tag to use.

Changing name does not really help. Best is to get a tag hich clearly indicates what works with a a given version of OpenCPN (e.g. v50). A standardisation of release tag names would be nice but a guessable name would do as well.

**Comment by rgleason** [comment]
I get it now Dominig.  Thanks.  

I've learned how to push tags, and how to get appveyor to push a new windows artifact to a new release on my repository, and I'm changing the version patch now.

I think the next thing to learn is how to make a pull request from my repository to Sean's for a new version Tag along with an increment to the Version Patch and Date in VERSION.cmake.  I've been doing releases manually on my repository, generally  without touching this..

One problem is that the Cmake varies from plugin to plugin so I will have to find where versioning is controlled.
