### ISSUE TITLE
Detect Boundary problem

### ISSUE THREAD

**Issue by xbgmsharp** [seandepagnier/weather_routing_pi#257]
Hello

I am running into the same issue as Detect Boundary problem #191 .
Could you clarified the process to make it work. Should we use the Chart Downloader or download for Older OpenCPN versions. I did method both with no success.
```
Failed to start configuration: Configuration specifies boundary exclusion but ocpn_draw_pi boundary data not available
```

- MacOSX
- OpenCPN_5.0.1+0266678
- Weather_routing-Plugin-macOS-ov50_1.13.0

```
$ ls Documents/Charts/GSHHG/
GSHHG_Catalog.xml	chartdldr_pi.dat	poly-c-1.dat		poly-f-1.dat		poly-h-1.dat		poly-i-1.dat		poly-l-1.dat

$ ls /Applications/OpenCPN.app/Contents/SharedSupport/gshhs/
poly-c-1.dat	poly-h-1.dat	poly-l-1.dat	wdb_borders_f.b	wdb_borders_i.b	wdb_rivers_c.b	wdb_rivers_h.b	wdb_rivers_l.b
poly-f-1.dat	poly-i-1.dat	wdb_borders_c.b	wdb_borders_h.b	wdb_borders_l.b	wdb_rivers_f.b	wdb_rivers_i.b

$ ls Documents/Charts/opencpn\ 2/gshhs/
poly-c-1.dat	poly-h-1.dat	poly-l-1.dat	wdb_borders_f.b	wdb_borders_i.b	wdb_rivers_c.b	wdb_rivers_h.b	wdb_rivers_l.b
poly-f-1.dat	poly-i-1.dat	wdb_borders_c.b	wdb_borders_h.b	wdb_borders_l.b	wdb_rivers_f.b	wdb_rivers_i.b
```

**Comment by rgleason** [comment]
The issue you reference has been closed and resolved. 

The error:
"Failed to start configuration: Configuration specifies boundary exclusion but ocpn_draw_pi boundary data not available"

Indicates that the boundary created in Ocpn_draw does not exist.  You need a boundary to exist first, then Weatherrouting can use it.

Please close this issue, and ask for help on the Cruiser Forum. Thanks.

**Comment by rgleason** [comment]
Will the OP please kindly close this Issue?

**Comment by rgleason** [comment]
@seandepagnier  Sean please close this. Thanks
