### ISSUE TITLE
std::length_error on "Options" opening

### ISSUE THREAD

**Issue by ghost** [seandepagnier/weather_routing_pi#26]
This plugin seems to make OpenCPN crash when I open the Options panel. The error I get is:
```
terminate called after throwing an instance of 'std::length_error'
  what():  basic_string::assign
Abandon
```

In OpenCPN logs, I have the following message:
```
PlugInManager searching for PlugIns in location /usr/local/lib/opencpn
PlugInManager: Loading PlugIn: /usr/local/lib/opencpn/libweather_routing_pi.so
```
Those are the last two lines, OpenCPN crashes right after it.

I built weather routing from sources, using wxWidgets 3.0 on my Raspberry Pi 2 with Raspbian (Debian version 7.8). The version of OpenCPN I have is built from sources too, it is not your optimized for Pi version though.

**Comment by rgleason** [comment]
I think we are on wxWidgets  3.0.2 now. that might be the problem.

**Comment by rgleason** [comment]
mbouyer, I think this is a completely separate problem. You should make a separate issue for it.

**Comment by rgleason** [comment]
ghost, did you get squared away with right version of wxwidgets? Can this be closed now?

**Comment by rgleason** [comment]
ghost?   It would help if you were to respond.
Sean I think you can close this now. He is not responding. I am not allowed to close it.

**Comment by rgleason** [comment]
Sean this needs to be closed. I can't close it. I'm not permitted.
