### ISSUE TITLE
1.13.7.1 CMakeList.txt broken with undefined GIT_REPOSITORY_BRANCH at line 96 

### ISSUE THREAD

**Issue by barjac** [seandepagnier/weather_routing_pi#267]
It's all in the summary. CMakeLists.txt arrives at line 96 without defining GIT_REPOSITORY_BRANCH.
If lines 96 and 99 are commented then it is defined at line 98 and the build completes.

**Comment by rgleason** [comment]
This Issue just came into Sean's repos  Sean's repos has and earlier PR from the current one. However this might apply? Maybe Jon already fixed that too.
1.13.7.1 CMakeList.txt broken with undefined GIT_REPOSITORY_BRANCH at line 96 #267

https://github.com/seandepagnier/weather_routing_pi/blob/master/CMakeLists.txt

Line 96 and 98

      execute_process(    <---Line 90
        COMMAND git rev-parse --abbrev-ref HEAD
        WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}
        OUTPUT_VARIABLE GIT_REPOSITORY_BRANCH
        OUTPUT_STRIP_TRAILING_WHITESPACE
        )
      if(${GIT_REPOSITORY_BRANCH} EQUAL "")    <---Line 96
        message(STATUS "Setting default GIT repository branch - master")
        set(GIT_REPOSITORY_BRANCH "master")
      endif()
      execute_process(

https://github.com/rgleason/weather_routing_pi/blob/master/cmake/PluginSetup.cmake

This code has moved to plugsetup.cmake and changed.
execute_process(
    COMMAND git log -1 --format=%h
    WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}
    OUTPUT_VARIABLE GIT_HASH
    OUTPUT_STRIP_TRAILING_WHITESPACE)

execute_process(
    COMMAND git log -1 --format=%ci
    WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}
    OUTPUT_VARIABLE GIT_COMMIT_DATE OUTPUT_STRIP_TRAILING_WHITESPACE)


I should probably make a new PR to Sean, once things settle down a little, but you might want to use more the recent code.
I think this can be closed.

**Comment by rgleason** [comment]
Also please note that there are several open PR!

**Comment by rgleason** [comment]
Please close this issue..  It refers to old code.

**Comment by barjac** [comment]
Thanks, I will wait 'until things settle down' before updating our package.

**Comment by rgleason** [comment]
you might want to look at rgleason/weather_routing_pi at that time

**Comment by barjac** [comment]
Thanks - I am never sure which source to use or which is a 'stable release'. Maybe you could clarify this for me?

**Comment by rgleason** [comment]
Right now weather_routing needs fixes for flatpak, but when it settles down try the master branch, but check "frontend2" as it may be slightly ahead, of the fork github.com/rgleason/weather_routing_pi   
I am trying to make PR's to sean too..

**Comment by rgleason** [comment]
This is quite old and should be closed now. The code has moved on.

@barjac  @seandepagnier  I believe this is probably fixed and in any case is old and should be closed. Please close it now. I cannot. Tnanks.
