### ISSUE TITLE
OpenCpn crash when track is delete

### ISSUE THREAD

**Issue by ldeschaumes** [seandepagnier/weather_routing_pi#269]
OpenCpn crash when track is deleted.
Config : Ubuntu  20.04 LTS
OpenCPN 5.2.0 compiled from source
plugin wheather 1.13.19.0

**Comment by rgleason** [comment]
This has nothing to do with weather-routing.

**Comment by seandepagnier** [comment]
this is opencpn issue not weather routing, and you need a backtrace or something.
