### ISSUE TITLE
Sail Plan and Switch Plan Rules - how to make entries?

### ISSUE THREAD

**Issue by rgleason** [seandepagnier/weather_routing_pi#27]
Thank you Sean,  
The menus are better and the settings more cohesive.
I like these improvements, it is more intuitive for users.

"Sail Plan" and "Switch Plan Rules" do not seem to work they way they used to.
 How does one enter values?  Something is not working here I believe.

**Comment by rgleason** [comment]
Sean, how does  "Sail Plan" and "switch plan rules" fit with the new configuration?
Has this been completely changed?
I thought we could set up the boat to motor at 5.5 knots when wind speed hit 5 knots with a special polar file.  How would we do thatt now?

**Comment by seandepagnier** [comment]
you create different polars and automatically the fastest one is used

**Comment by rgleason** [comment]
Going to close this now.
