### ISSUE TITLE
Weather_routing plugin hangs OpenCPN on arm32 rpi 

### ISSUE THREAD

**Issue by mgrouch** [seandepagnier/weather_routing_pi#270]
Weather_routing plugin hangs OpenCPN on arm32 rpi 

To be honest climatology and pypilot plugins crash OpenCPN too under some circumstances.

The simplest way (that I can come up with) to reproduce the issues is to:

1. Download latest armhf SD card image of https://github.com/bareboat-necessities/lysmarine_gen
 from here https://cloudsmith.io/~bbn-projects/repos/bbn-repo/packages/?q=lysmarine

2. Boot from it and start OpenCPN, while connected to internet update the OpenCPN plugins from \
OpenCPN itself (Tools/Options/Plugins) and update one by one the ones which have green arrow
indicating that update is available.

to start pypilot server

sudo systemctl start pypilot@pypilot

Thanks,
--mg

**Comment by rgleason** [comment]
Well, I am going to be updating shortly today, can you try the new version when it arrives?  Sorry but I have no way of testing, so your help is much appreciated.

You say climatology has the same issue?

**Comment by mgrouch** [comment]
Sure. Let me know when I can try

Thanks

**Comment by rgleason** [comment]
Mike, we can close this now I believe.  Will you please close it?  Only you or Sean can close it. I can't.  Thanks.
