### ISSUE TITLE
Routing solutions with unrealistic apparent wind angles

### ISSUE THREAD

**Issue by manueldeljesus** [seandepagnier/weather_routing_pi#271]
I am running Weather Routing 1.13.19.0 over OpenCPN 5.2.4 on Windows 10.

Many optimal solutions result in tacks against the wind, with apparent angles well below 10º, and even almost zero. I have tried with different polars and I get the same results. Any ideas as to what I may be doing wrong?

Thanks in advance

**Comment by seandepagnier** [comment]
check your polar and if "optimize tacking" is enabled as an option

See the manual, but basically this assumes the boat tacks at best vmg to follow weather route.

**Comment by manueldeljesus** [comment]
Effectively, "optmize tacking" was enabled, but because the simulation does not complete unless I set that option. Additional tests have shown that if I reduce the time step, the simulation ends, however, the solution seems weird. I will analyze and get back to you.

Any reason why the time step may be problematic? May it be that I start too close to a boundary?

Your help is really appreciated

**Comment by rgleason** [comment]
Have you been stepping through grib time and watching your boat position move and wind direction change? Those indications would be what the predictive grib file anticipates, and the boat action is dependent on the polar file used.

"...the solution seems weird... is not something we can respond to. Perhaps if you gave use greater description of what you are doing, what your settings are and some screeenshots, we could help.

But, this is not a "help" area. You should be using the Cruiser Forum for that.

Please close this if it is just a help issue.

**Comment by rgleason** [comment]
Can this be closed now by the OP, please?

**Comment by rgleason** [comment]
OR show us the situation by attaching screenshots and files used please.

**Comment by rgleason** [comment]
Sean you are the only one who can close this one.
