### ISSUE TITLE
What is branch "Crossover"?  Is that what I should be building? I've been building "master"

### ISSUE THREAD

**Issue by rgleason** [seandepagnier/weather_routing_pi#44]
This may be the problem I have been having with Windows!????

**Comment by seandepagnier** [comment]
crossover was my work inprogress.

Use master

**Comment by rgleason** [comment]
Just tried to build Crossover with MSVC++ Windows. See attached.
[Weather_routing_Crossover_Branch.txt](https://github.com/seandepagnier/weather_routing_pi/files/317234/Weather_routing_Crossover_Branch.txt)

**Comment by rgleason** [comment]
Am back to building "Master" now closing.
