### ISSUE TITLE
Segfault when no grib files are loaded

### ISSUE THREAD

**Issue by mbouyer** [seandepagnier/weather_routing_pi#45]
Hello,
testing the new opencpn and newer plugins I ran into this issue:
when opening the grib plugin *without any grib file loaded*, then weather_routing, I get a segfault.
First I get a wxASSERT:
ASSERT INFO:
/local/armandeche1/tmp/pkgbuild/geography/opencpn/work/.buildlink/include/wx-3.0/wx/dynarray.h(838): assert "uiIndex < m_nCount" failed in Item().

BACKTRACE:
[1] PlugInManager::SendMessageToAllPlugins(wxString const&, wxString const&) /local/armandeche1/tmp/pkgbuild/geography/opencpn/work/OpenCPN-ec4fb21cf1f8f0a8e6bd6768a235699fc76848a2/src/pluginmanager.cpp:1492
[2] SendPluginMessage /local/armandeche1/tmp/pkgbuild/geography/opencpn/work/OpenCPN-ec4fb21cf1f8f0a8e6bd6768a235699fc76848a2/src/pluginmanager.cpp:2396
[3] MyFrame::OnToolLeftClick(wxCommandEvent&) /local/armandeche1/tmp/pkgbuild/geography/opencpn/work/OpenCPN-ec4fb21cf1f8f0a8e6bd6768a235699fc76848a2/src/chart1.cpp:4254
[4] main /local/armandeche1/tmp/pkgbuild/geography/opencpn/work/OpenCPN-ec4fb21cf1f8f0a8e6bd6768a235699fc76848a2/src/chart1.cpp:831

If I click "continue" then I get this segfault:
Program received signal SIGSEGV, Segmentation fault.
[Switching to LWP 1]
0x00007f7fdd33d577 in ArrayOfGribRecordSets::Item (this=0x7f7fefb4b568, 
    uiIndex=0)
    at /local/armandeche1/tmp/pkgbuild/geography/opencpn/work/OpenCPN-ec4fb21cf1f8f0a8e6bd6768a235699fc76848a2/plugins/grib_pi/src/GribUIDialog.h:66
66      WX_DECLARE_OBJARRAY( GribRecordSet, ArrayOfGribRecordSets );
(gdb) where 
#0  0x00007f7fdd33d577 in ArrayOfGribRecordSets::Item (this=0x7f7fefb4b568, 
    uiIndex=0)
    at /local/armandeche1/tmp/pkgbuild/geography/opencpn/work/OpenCPN-ec4fb21cf1f8f0a8e6bd6768a235699fc76848a2/plugins/grib_pi/src/GribUIDialog.h:66
#1  0x00007f7fdd298dd1 in GRIBUICtrlBar::TimelineTime (this=0x7f7fec70b000)
    at /local/armandeche1/tmp/pkgbuild/geography/opencpn/work/OpenCPN-ec4fb21cf1f8f0a8e6bd6768a235699fc76848a2/plugins/grib_pi/src/GribUIDialog.cpp:1257
#2  0x00007f7fdd25c55f in grib_pi::SetPluginMessage (this=0x7f7ff1bc4380, 
    message_id=..., message_body=...)
    at /local/armandeche1/tmp/pkgbuild/geography/opencpn/work/OpenCPN-ec4fb21cf1f8f0a8e6bd6768a235699fc76848a2/plugins/grib_pi/src/grib_pi.cpp:535
#3  0x00000000007eb4c3 in PlugInManager::SendMessageToAllPlugins (
    this=0x7f7ff776e770, message_id=..., message_body=...)
    at /local/armandeche1/tmp/pkgbuild/geography/opencpn/work/OpenCPN-ec4fb21cf1f8f0a8e6bd6768a235699fc76848a2/src/pluginmanager.cpp:1491
#4  0x00000000007ee9bf in SendPluginMessage (message_id=..., message_body=...)
    at /local/armandeche1/tmp/pkgbuild/geography/opencpn/work/OpenCPN-ec4fb21cf1f8f0a8e6bd6768a235699fc76848a2/src/pluginmanager.cpp:2389
#5  0x00007f7fdca73c14 in weather_routing_pi::OnToolbarToolCallback (
    this=0x7f7ff3b7d340, id=<optimized out>)
    at /local/armandeche1/tmp/pkgbuild/geography/opencpn-plugin-weather_routing/work/weather_routing_pi-264605a7a9e3b33e10bbd2375a7d3fd55518b3dc/src/weather_routing_pi.cpp:358
#6  0x00000000005c89e8 in MyFrame::OnToolLeftClick (this=0x7f7ff6b7c000, 
    event=...)
    at /local/armandeche1/tmp/pkgbuild/geography/opencpn/work/OpenCPN-ec4fb21cf1f8f0a8e6bd6768a235699fc76848a2/src/chart1.cpp:4254
#7  0x00007f7ff4c8f84e in wxAppConsoleBase::CallEventHandler(wxEvtHandler*, wxEventFunctor&, wxEvent&) const () from /usr/pkg/lib/libwx_baseu-3.0.so.0
#8  0x00007f7ff4dbf967 in wxEvtHandler::ProcessEventIfMatchesId(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&) ()
   from /usr/pkg/lib/libwx_baseu-3.0.so.0
#9  0x00007f7ff4dbfa04 in wxEventHashTable::HandleEvent(wxEvent&, wxEvtHandler*) () from /usr/pkg/lib/libwx_baseu-3.0.so.0
#10 0x00007f7ff4dbfcf9 in wxEvtHandler::TryHereOnly(wxEvent&) ()
   from /usr/pkg/lib/libwx_baseu-3.0.so.0
#11 0x00007f7ff4dbfb41 in wxEvtHandler::DoTryChain(wxEvent&) ()
   from /usr/pkg/lib/libwx_baseu-3.0.so.0
#12 0x00007f7ff4dbfda8 in wxEvtHandler::ProcessEvent(wxEvent&) ()
   from /usr/pkg/lib/libwx_baseu-3.0.so.0
#13 0x00007f7ff55ee582 in wxWindowBase::TryAfter(wxEvent&) ()
   from /usr/pkg/lib/libwx_gtk2u_core-3.0.so.0
#14 0x00007f7ff4dc0c89 in wxEvtHandler::ProcessPendingEvents() ()
   from /usr/pkg/lib/libwx_baseu-3.0.so.0
#15 0x00007f7ff4c92bcc in wxAppConsoleBase::ProcessPendingEvents() ()
   from /usr/pkg/lib/libwx_baseu-3.0.so.0
#16 0x00007f7ff54985d8 in wxApp::DoIdle() ()
   from /usr/pkg/lib/libwx_gtk2u_core-3.0.so.0
#17 0x00007f7ff54986cf in wxapp_idle_callback ()
   from /usr/pkg/lib/libwx_gtk2u_core-3.0.so.0
#18 0x00007f7ff1044099 in g_main_context_dispatch ()
   from /usr/pkg/lib/libglib-2.0.so.0
#19 0x00007f7ff104438a in g_main_context_iterate.isra ()
   from /usr/pkg/lib/libglib-2.0.so.0
#20 0x00007f7ff1044621 in g_main_loop_run () from /usr/pkg/lib/libglib-2.0.so.0
#21 0x00007f7feed2e90f in gtk_main () from /usr/pkg/lib/libgtk-x11-2.0.so.0
#22 0x00007f7ff54a823d in wxGUIEventLoop::DoRun() ()
   from /usr/pkg/lib/libwx_gtk2u_core-3.0.so.0
#23 0x00007f7ff4cc7a98 in wxEventLoopBase::Run() ()
   from /usr/pkg/lib/libwx_baseu-3.0.so.0
#24 0x00007f7ff4c91468 in wxAppConsoleBase::MainLoop() ()
   from /usr/pkg/lib/libwx_baseu-3.0.so.0
#25 0x00007f7ff4d0c401 in wxEntry(int&, wchar_t**) ()
   from /usr/pkg/lib/libwx_baseu-3.0.so.0
#26 0x00000000005b6f3b in main (argc=2, argv=0x7f7fffffd9f8)
    at /local/armandeche1/tmp/pkgbuild/geography/opencpn/work/OpenCPN-ec4fb21cf1f8f0a8e6bd6768a235699fc76848a2/src/chart1.cpp:831

If I do not open the grib plugin before weather_routing I get no assert and no segfault.

**Comment by seandepagnier** [comment]
thanks for the report.. the bug is actually in the grib plugin I made a pull request to fix, see:

https://github.com/OpenCPN/OpenCPN/pull/662
