### ISSUE TITLE
Saving a boat would require to run OpenCPN as "root"

### ISSUE THREAD

**Issue by dominig** [seandepagnier/weather_routing_pi#49]
OpenCPN 4.4 Linux OpenSUSE.

The plugin requires to create a new boat to make a calculation.
But it tried to save it in the general OpenCPN plugin directory while it should write in $HOME/.opencpn/plugins/weather_routing/
but it tries to write in /usr/share/opencpn/plugins/weather_routing_pi/data/polars/boat_A35.pol.contours
which is rejectected

![weatheroutingbug1](https://cloud.githubusercontent.com/assets/1193120/16668477/72b2e15e-4491-11e6-9c09-2dfcc53c2c35.png)

**Comment by seandepagnier** [comment]
should be fixed
