### ISSUE TITLE
Latitudes South or Longitudes West

### ISSUE THREAD

**Issue by Rasbats** [seandepagnier/weather_routing_pi#56]
WeatherRouting::OnNewPosition( wxCommandEvent& event )

If you use the menu to add a new position (instead of right-click). For negative latitude/longitude i.e. south or west the function lat+=lat_minutes/60 produces the wrong answer.

e.g.  (4deg 30mins West)  = -4 + 30/60 = -3.5 instead of -4.5  

Perhaps a drop-down for N/S, E/W would fix this.

**Comment by seandepagnier** [comment]
I think it's fixed now
