### ISSUE TITLE
manual page point to an invalid web page

### ISSUE THREAD

**Issue by dominig** [seandepagnier/weather_routing_pi#60]
Start the weather_routing_pi
select the manual from the Helpmenu item.
Will start a browser on an empty page.

**Comment by rgleason** [comment]
The correct wxRoute manual page is

https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:opencpn_user_manual:toolbar_buttons:plugins:weather:weather_routing

**Comment by seandepagnier** [comment]
updated

**Comment by rgleason** [comment]
Thanks Sean
