### ISSUE TITLE
French translation of menu show a digit before text item.

### ISSUE THREAD

**Issue by dominig** [seandepagnier/weather_routing_pi#61]
When starting the pluginin a French env.
the two last menu item are shown with a digit before the text.
2:Voir
5:Aide
Strange, looks like s shift somewhere.

**Comment by rgleason** [comment]
dominig,

I checked both occurances in the french pot file using Poedit and they do not seem to be the problem!
I removed each and retyped  Voir and Aide and then saved it back to crowdsource, but I don't think that is the problem.  Perhaps it is something extraneous in the program?

**Comment by stelian42** [comment]
Should be fixed in pull request: "I18N updates #96"

**Comment by rgleason** [comment]
Dominig,  Can this be closed now?  I believe it is fixed.

**Comment by dominig** [comment]
Nice.
Merci beaucoup.
![screenshot_20180123_133352](https://user-images.githubusercontent.com/1193120/35276019-19d44ce4-0042-11e8-81a4-4bfbad530f40.png)
