### ISSUE TITLE
Documentation on how to load polar is completly out of sync with the code

### ISSUE THREAD

**Issue by dominig** [seandepagnier/weather_routing_pi#62]
A minimum documentation on how to enter a Polar is missing and the old documentation is completly out of sync with the code.

**Comment by rgleason** [comment]
The manual is completely rewritten, but also needs some work.
https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:opencpn_user_manual:toolbar_buttons:plugins:weather:weather_routing#wr_configuration_-_boatxml_menu_-_edit

**Comment by rgleason** [comment]
This can be closed. I can't close it.
