### ISSUE TITLE
Create new route: Time actions display an real not a time

### ISSUE THREAD

**Issue by dominig** [seandepagnier/weather_routing_pi#63]
When creating a new route, you have the option to select the time from the Grib (do not know what it actually means) and current time (easier to guess).

Both action will display a real which I guess is the time in GMT in decimal.
My system is setup to use local time, but I am not sure that the plugin reads that setting.
(might be a second bug) but not testable for the ime as the plugin is broken for me.

**Comment by seandepagnier** [comment]
The grib time is whatever the grib time slider is set to.

**Comment by dominig** [comment]
I guess I was not very clear. My screen shot should help.
Time in that combo box needs to be entered in decimal hours (you seem to expect local time) what is less than obvious.
So to enter 
 - 11:30 you need to type 11.5
 - 11:59 "                        " 11.98 (see joined 1st screenshot)
Once the route is calculated,  the time is displayed correctly (see 2nd screenshot).

reports miss date and that is reported in issue #64
![1_timeindecimal-screenshot_20170331_112018](https://cloud.githubusercontent.com/assets/1193120/24545214/9c82d308-1606-11e7-9b68-237f3990b173.png)
![2_routetablewithcorrecttimeinfo-screenshot_20170331_113119](https://cloud.githubusercontent.com/assets/1193120/24545218/a162772a-1606-11e7-9029-d68b9ac644bf.png)

**Comment by seandepagnier** [comment]
Do you suggest supporting hh:mm in utc time instead?

**Comment by dominig** [comment]
Sean,

I would suggest to support the input and display format hh:mm, as it's the most use internationally.
Decimal hours is used by no one except mathematicians.
For Local vs GMT, I personally think that most user plan their route in local time, but as OpenCPN as a configuration tag for local/GMT, this is what should dictate the operational model. I do not know if the information is available from the API, but the date format is in anycase available in .opencpn/opencpn.cong (tag TrackRotateTimeType)
Obviously remember the selected value in the report table, is needed as error can make a huge difference in some part of the world (not to bad in Europe/UK)

**Comment by rgleason** [comment]
See Report Time as well as date   
https://github.com/seandepagnier/weather_routing_pi/commit/32d0042a9993a8f83668df86b677a098d15a3cd0

Perhaps this can be closed?

**Comment by rgleason** [comment]
reportdialog.cpp
         page += _("Route from ") + c.Start + _(" to ") + c.End + _T("<dt>");
-        page += _("Leaving ") + c.StartTime.Format(_T("%x")) + _T("<dt>");
-        page += _("Arriving ") + (*it)->EndTime().Format(_T("%x")) + _T("<dt>");
+        page += _("Leaving ") + c.StartTime.Format(_T("%x %X")) + _T("<dt>");
+        page += _("Arriving ") + (*it)->EndTime().Format(_T("%x %X")) + _T("<dt>");
         page += _("Duration ") + ((*it)->EndTime() - c.StartTime).Format() + _T("<dt>");

Can this be closed?

**Comment by stelian42** [comment]
No this is still an outstanding issue. GMT issues were hopefully fixed but the "Start time" input textfield should accept a hh:mm value instead of a hh.hh value.

**Comment by rgleason** [comment]
It looks to me like the Time input has changed. Has this solved he problem?
(I'd like to see more space for the variouus time slots!!)

![wxrte-time](https://user-images.githubusercontent.com/2363959/35234002-c132d9d6-ff6d-11e7-9800-8f8d99dfc476.png)

**Comment by dominig** [comment]
It's getting better.
+ Time is local (most use will be like that)
+ hours are separated from the minutes
+ date format is aligned with language selection

- the accuracy to the second with a decimal point on the minutes is not of any use but not dangerous, just confusing.

Good enough to close.

**Comment by rgleason** [comment]
> the accuracy to the second with a decimal point on the minutes is not of any use but not dangerous, just confusing

Maybe we should fix this, so it's good.

.

**Comment by dominig** [comment]
Look at the snapshot. You will notice that on Linux the entry for the minutes take a decimal which take the seconds. Field seems to accept any value.
Not a real issue as no one would ever plan a start route in seconds.
But presentation looks strange.
![screenshot_20180123_173519](https://user-images.githubusercontent.com/1193120/35288008-f8e31ac0-0063-11e8-93fb-a86dc661f3d0.png)
