### ISSUE TITLE
Route report does not show time

### ISSUE THREAD

**Issue by dominig** [seandepagnier/weather_routing_pi#64]
The report after a route calculation does not show the time (only the date).
It would be nice to show the time ideally in local and GMT as once far away mistake can happen.
![routereportmissingtime-screenshot_20170331_112808](https://cloud.githubusercontent.com/assets/1193120/24545180/74ddd1f4-1606-11e7-90ca-3b2339996558.png)

**Comment by rgleason** [comment]
Yes a needed fix.
The report after a route calculation does not show the time (only the date).
It would be nice to show the time ideally in local and GMT as once far away mistake can happen.

**Comment by seandepagnier** [comment]
implemented
