### ISSUE TITLE
Calculation on grib alone fails

### ISSUE THREAD

**Issue by norulz** [seandepagnier/weather_routing_pi#7]
Using weather_routing_pi-1.2-ov3.3.2410-win32 on opencpn_3.3.2410_setup.

Calculation of routes appears to be using climatology only even with grib files loaded. If climatology is turned off - "disabled" then the calculation fails with grib failure status.

Went back to OpenCPN 3.3.2316 with WR weather_routing_pi-1.2-ov3.3.2107-win32 and all seems to be OK.

David

**Comment by norulz** [comment]
Weather routing still not working with gribs using OpenCPN_3.3.2503 and WR 1.2-ov3.3.2410.
Can you suggest which versions are compatible

**Comment by rgleason** [comment]
Over Christmas wx_routing was working with Grib alone, just fine.
No change in wx_routing needed, just updated Opencpn 3.3.2430 to work better with plugins and 1.12api as I understand it.  Be sure you have a current grib and set the date and time.
It should work with 3.3.2503 but I have not tried yet.  Also try creating a total NEW config with new wpts etc.

**Comment by nohal** [comment]
There is no problem with OpenCPN 3.3.2503 and the weather routing plugin from opencpn.org. Tested.
This issue can be closed.

**Comment by rgleason** [comment]
Don't have time to test now, but I am quite sure it works. Your grib routing is not worrking, but Climatology is.  That suggests that you may need to get your grib time correct. Turn off climatology and uslect the climatology running in the wx_route config. Then go through the settings on the left of config.
No need to go into sub menus.  See if it works. Download a new grib file, select it. In wx_route set the date and time. Make a new route configuration with start and end. Then try to run it.

**Comment by norulz** [comment]
Checked with new grib file and correct dates/times. New configuration etc. Does not work even with climatology disabled and uninstalled!
Second time clean install without climatology -- works fine.
Installed climatology --> continued to work fine so I looked for another source of the problem
Once I started selecting various polars, calculation failed. Using sailboat transform -- all is fine again.
Note Grib is showing beam winds of above 30 - 40 kts.
Perhaps calculation failure is when wind is beyond polar settings??

**Comment by norulz** [comment]
Loaded a historic grib with winds < 30kt and all works fine even with polars. (I tried several)
Seems that stronger winds and polars are creating the problem.

**Comment by norulz** [comment]
Hi Rick,
How can I send you the relevant Grib file, polar and WeatherRoutingConfiguration.xml file. 
Calculation fails with this particular set of files and succeeds with the same domain of Grib files but from a different date with less wind.
I believe it is a good idea to try to recreate the issue on your machine.

Thanks,
David

**Comment by rgleason** [comment]
David can you pm me on the opencpn forum? Where  you should be able to give me your email. Then i'lll give you mine. Other way is through gothub somehow...how else?  Could leave files on weather route theead maybe.

**Comment by seandepagnier** [comment]
If your polar doesn't include boat speeds above a windspeed that the grib
tries to use, it will fail to route.  It should not fall back on
climatology in this case, please inform me if you found this.

**Comment by rgleason** [comment]
Thanks Sean, very helpful. David, try to just add some info for higher wind speeds to your polar file with an approximation, see if it works. You can use a text editor, see if it works, (but be careful about hard returns, sometimes it makes a difference.

**Comment by norulz** [comment]
Rick and Sean,
I beefed up the polar to 40kts as suggested and can confirm that it calculates OK. With the old polar when it fails there is no fall back to climatology even if it is selected as available.
Thanks for putting this to rest.
David

**Comment by rgleason** [comment]
P
I had an idea.  Maybe the weather royting plugin could use the unkown polarcspeeds as an upper limit consyraint and flag ut with a meassage "polar upper limit reached, now routinf arround those higher winds" and the config constraint tablw shows tha wind speed as an upper limit?  Sorry about small text.

**Comment by seandepagnier** [comment]
So it could display a warning in the status that maximum wind for the
specified polar had been exceeded?

**Comment by rgleason** [comment]
Yes that would be good and perhaps just continue routing around the high winds too with the warning!

**Comment by rgleason** [comment]
Grib wind speed exceeds polar data. 

 Some ways to handle it:
1. Display a warning in the status that maximum wind for the specified polar had been exceeded?
2.  Use the unknown  polar upper wind speeds as constraint with a message  "polar upper limit reached, now routing around the higher winds" and the  config constraint table shows that wind speed as an upper limit.

I am going to close this and open an new one. ..Perhaps Sean has made improvements.

**Comment by rgleason** [comment]
This issue should be closed and I can't close it.
