### ISSUE TITLE
after editing a Polar it cannot be saved

### ISSUE THREAD

**Issue by dominig** [seandepagnier/weather_routing_pi#70]
- Open an existing polar
- change som evalue
- try to save
!! you get an error because a standard user cannot write in System directories
   (see joined image)
Possible solutions
 - save in the ~/.opencpn/plugin/weatherrouting (hiden data are never friendly)
 - ask where to save (preferable)
 - give rw to the group dailout (required to access the GPS anyhow) (Bad practice but would work)
![screenshot_20170419_125501](https://cloud.githubusercontent.com/assets/1193120/25176895/1823412a-2500-11e7-9761-f3368d01c2d1.png)

**Comment by rgleason** [comment]
For Windows,  Polars are currently under (programfilesx86)

Same problem
> try to save 
> !! you get an error because a standard user cannot write in System directories
> (see joined image)
> 

1. Windows: Work out of programdata/opencpn/weather_routing/polars  (preferred)
2. Or ask where to save

**Comment by rgleason** [comment]
Sean, I have some extensive testing and summary on this. Will upload later.

**Comment by rgleason** [comment]
This is fixed now I believe and it can be closed.  I cannot close it. Sean or Dominiq

**Comment by rgleason** [comment]
Correction: Under the Polar Edit > Dimension TAB    Try to add an additional TWS at the top end. It gets added to the bottom and appears, but try to "SAVE" the file next. There is a hangup and OpenCPN crashes.

**Comment by rgleason** [comment]
This is fixed now. Sean or Dominiq  you can close it now. I can't.

**Comment by dominig** [comment]
Thanks
