### ISSUE TITLE
Route will not show if grib plugin is open

### ISSUE THREAD

**Issue by dominig** [seandepagnier/weather_routing_pi#71]
Open Grib plug in with valid data
Calculate a route
Route will not show as long as the Grib plug in is open.
See screenshots

![screenshot_20170419_194442](https://cloud.githubusercontent.com/assets/1193120/25194033/620f33b4-2539-11e7-989c-bacc637476df.png)
![screenshot_20170419_194548](https://cloud.githubusercontent.com/assets/1193120/25194093/947c3388-2539-11e7-9c49-7dfeea388d56.png)

**Comment by rgleason** [comment]
The plugin works correctly. Isn't this fixed in your OS now?
Perhaps this should be closed?

**Comment by dominig** [comment]
With last release tested with OpenCPN 4.8, I cannot read a polar file correctly, so the plugin fails.
See snap shot of the Polar created from a test polar (also joined).
![screenshot_20180123_113653](https://user-images.githubusercontent.com/1193120/35271297-eee01c6c-0031-11e8-8f04-dec3d28cff47.png)

[boat_A35.pol.zip](https://github.com/seandepagnier/weather_routing_pi/files/1655513/boat_A35.pol.zip)

**Comment by stelian42** [comment]
You need to activate OpenGL in order to have the route display on top of the grib layer !

**Comment by stelian42** [comment]
I loaded your polar, and successfully did a routing using it...

**Comment by dominig** [comment]
Then we may have a Linux specific problem (or worse an OpenSUSE specific) because I cannot load that polar.
As you can see on the graph, there is a blue line that is completely wrong and fails the plugin.

**Comment by dominig** [comment]
It seems that an issue on the polar reader is still present but the display over grib works.
(I have always used OpenGL).
I will try to isolate the Polar graph display  issue (obvious on the snapshot), it might leads me to the failure that I see with some polar where route refuse to calculate.
Then I will reopen a new more focused bug if needed.

**Comment by stelian42** [comment]
In fact I also see the strange blue and the violet lines ! But the route completes fine, maybe this is only a bug in the drawing of the polar...

**Comment by stelian42** [comment]
I'm trying to understand the code, and from what I see, those lines have something to do with the VMG (see BoatDialog.cpp around line 431)

**Comment by stelian42** [comment]
And there are two of them because one is upwind, the other is downwind.  Now it remains to be seen if the values have some meaning or not...
