### ISSUE TITLE
Configured boat name is not readible even when enlarging the UI box

### ISSUE THREAD

**Issue by dominig** [seandepagnier/weather_routing_pi#72]
Configure a boat
Come back to route creation
The name of the boat cannot be read.

Idea for fix
 - show in that box the file name of the file without the directory path without the extension.
   (obviously the full name needs to be still use :-)

![screenshot_20170419_204356](https://cloud.githubusercontent.com/assets/1193120/25197008/bba968be-2542-11e7-9092-e5b5d8ace815.png)

**Comment by seandepagnier** [comment]
The problem with only showing the name without path is if two boats with different path but same name exist.   In this case, it would break multiple configuration which is fully supported (selecting more than one configuration and editing) when the boats have the same filename but different path.

I implemented a different "fix" it simply scrolls to the right all the way automatically. I hope this helps.

**Comment by dominig** [comment]
Fix verfified an integrated (in OpenSUSE).
Thanks. Dominig
![screenshot_20170422_103112](https://cloud.githubusercontent.com/assets/1193120/25302807/0a86e6a4-2747-11e7-812d-9fca060bb86b.png)
