### ISSUE TITLE
First time Install to a "clean" OpenCPN 

### ISSUE THREAD

**Issue by rgleason** [seandepagnier/weather_routing_pi#78]
After removing all of weather_routing using "uninstall_weather_routing" and checking opencpn.ini to be sure all remnants of weather_routing settings were removed, the plugin was installed and notes made about how a new user would experience the installation.

First it should be emphasized that wxRoute is a wonderful plugin and there are many skilled users.  Sean has worked hard to make it friendly to a new user, but for this particular plugin it is a difficult task because it uses data from multiple sources and is dependent on boat polar data, gribs, climatology, etc.

Attached is WxRoute-First-time-Install.doc which reviews the process step by step.

[WxRoute-First-Time-Install.pdf](https://github.com/seandepagnier/weather_routing_pi/files/1312674/WxRoute-First-Time-Install.pdf)

Perhaps we can make some changes, which are outlined in the next post?

Summary
1. Include some files in the repository for Tutorial and startup. The wxRoute Manual has been rewritten (some filename changes needed) and I would like to include example files in the plugin, along with a sample _weatherRoutingConfiguration.xml_ and _Boat.xml_ & _Boat-test.xml_ files for New Users. I think these files will help users get started.
3. Change the locations of some files being installed to programdata. 
4. Check some of the pathnames being used for "open" and "save" files, etc.
5. Fix a couple of bugs.

**Comment by rgleason** [comment]
FURTHER SUMMARY from test

There are some installation details that will help all Users:

1. C:\ProgramData\opencpn\plugins\weather_routing\*.html
Install to C:\Program Files (x86)\OpenCPN 4.8.0\plugins\weather_routing_pi\

    WeatherRoutingInformation.html  (as is done now)
    info.html  (as is done now)

2. C:\Program Files (x86)\OpenCPN 4.8.0\plugins\weather_routing_pi\WeatherRoutingConfiguration.XML file
Install to  C:\ProgramData\opencpn\plugins\weather_routing\   (and used out of)
Rather than C:\Program Files (x86)\OpenCPN 4.8.0\plugins\weather_routing_pi\
Create this default file from hardcoded program (or copy  at installation):

    WeatherRoutingConfiguration.XML  (Full Reset, completely overwrites to default)

3. C:\Program Files (x86)\OpenCPN 4.8.0\plugins\weather_routing_pi\data\boat Directory:
Install to  C:\ProgramData\opencpn\plugins\weather_routing\boat (and used out of)
Rather than C:\ProgramData\opencpn\plugins\weather_routing
Otherwise the XML files may be confused by Users, (different purposes) so different directories & hierarchy.
Create these default files from hardcoded program (or copy at installation):

    Boat.XML       (Full Reset, completely overwrites to default)
    Boat-Test.XML  (Full Reset, completely overwrites to default)

4. C:\Program Files (x86)\OpenCPN 4.8.0\plugins\weather_routing_pi\data\polars Directory:  
Install Directory to  C:\ProgramData\opencpn\plugins\weather_routing\polars
Rather than C:\Program Files (x86)\OpenCPN 4.8.0\plugins\weather_routing_pi\data\polars
For the rewritten Manual and new Users,  add the following Polar files
Create these default files from hardcoded program (or copy at installation): 

    TWS-20-60.pol,
    TWS-6-20.pol,
    TWS-0-6-Power.pol
    Test-TWS-0-20+60.pol

5. C:\Program Files (x86)\OpenCPN 4.8.0\plugins\weather_routing_pi\data\grib-sample Directory:  
Install Directory to  C:\ProgramData\opencpn\plugins\weather_routing\grib-sample
For the rewritten Manual and Tutorial for new Users, add the following Grib file.

    Irma-Jose-20170907.grib2,

6. In Edit > Boat.xml Polar section, Add >Select Polar File path should default to C:\ProgramData\opencpn\plugins\weather_routing\polars

7. At the bottom of Configuration Menu provide "Partial Config Reset"  and  "Full Reset"  (with warning)  buttons.

8. Check that the program operates as expected with the configuration changes, particularly path names.

    Directory C:\ProgramData\opencpn\plugins\weather_routing\  

    - Boat
    - Contours  (created by the plugin)
    - Grib-Sample
    - Polars
    - WeatherRoutingConfiguration.XML   file

9. Check that the  wxFormbuilder files are working properly.

       weather_routing.fpb
       weather_routingUI.h
       weather_routingUI.cpp

Menus  are opening small and resizing when field data becomes available,
The wxRoute Configuration Menu does not shrink vertically as much as before, a stop setting at that height may be required.

10. Other Issues
-- Crossover Diagrams don't show in Windows.
-- Edit > Polar  Dimensions Tab check that this does not bomb Opencpn. Check operaton of all Tabs.
-- Edit > Polar Generate Tab  Measurements and Boat Characteristics VPP, Check operation
-- Update Internationalization?
-- Update version number & tag

**Comment by rgleason** [comment]
After Weather_Routing_pi has been installed, the Weather_Routing_Setup Package can be downloaded and unzipped to the directory "C:\ProgramData\opencpn\plugins\weather_routing".
Which will make these directories and file:
   *  boat
   * grib-sample
   * polars
   * WeatherRoutingConfiguration.XML
Once the full instructions are followed in the Manual for 
[Weather Routing Setup](https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:opencpn_user_manual:toolbar_buttons:plugins:weather:weather_routing&s[]=weather&s[]=routing#weather_routing_setup)

**Comment by rgleason** [comment]
It would be nice to have the [Weather Routing Setup](https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:opencpn_user_manual:toolbar_buttons:plugins:weather:weather_routing&s[]=weather&s[]=routing#weather_routing_setup) included in the program package.

**Comment by rgleason** [comment]
I have made a separate branch in my forked repository "Weather-Routing-Setup"
https://github.com/rgleason/weather_routing_pi/tree/Weather-Routing-Setup

and have made a Beta Release  which adds the files for the setup
https://github.com/rgleason/weather_routing_pi/releases

Then when trying to install to a clean setup, I found that several routings no longer worked (no matter what I did)  This is very disappointing.  I am going to pause on this effort at this point.



Here are my notes taken during the Install to a "clean" version of Opencpn showing what has to be done to make the plugin work properly.

**Install into a "clean" Opencpn with no Weather_Routing_pi**

1. Directories & Files under "data"
installed into: C:\Program Files (x86)\OpenCPN 4.8.0\plugins\weather_routing_pi\data
should have installed into: C:\ProgramData\opencpn\plugins\weather_routing\
   -  boat
  -   grib-sample
  -   polars
   -  WeatherRoutingConfiguration.XML

The subdirectory for these specific directories and files must be changed.

Oddly, the directory is created during install, I found:
C:\ProgramData\opencpn\plugins\weather_routing

---------
---------

In the OPENCPN.INI file there do not appear to be any wx_routing pathnames yet.
Open Weather_Routing_pi and the Configuration menu is empty.

Go to File > Open and the path is
C:\ProgramData\opencpn\plugins\weather_routing
So that is OK. There is a newly created empty weatherRoutingConfiguration.XML file in that directory that is blank.

Make two quick WeatherRoute Positions start and finish.
Go to Configuration > New   and set the start and end.

Open the Configuration again.
Go to Boat section  > ...   > Pathname/file

The path is to:  C:\ProgramData\opencpn\plugins\weather_routing
but it should be to: C:\ProgramData\opencpn\plugins\weather_routing\boat
And there is no "boat" directory here.

Now I have to copy boat directory over to
C:\ProgramData\opencpn\plugins\weather_routing\
Same with Polars and Grib-sample directory.
Might as well copy weatherconfiguration.XML all to
C:\ProgramData\opencpn\plugins\weather_routing\

Had to copy
  - boat
  - grib-sample
  - polars
  - WeatherRoutingConfiguration.XML

from C:\Program Files (x86)\OpenCPN 4.8.0\plugins\weather_routing_pi\data
to  C:\ProgramData\opencpn\plugins\weather_routing

Overwriting the WeatherRoutingConfiguration.XML file that was there.

Now when I go back to  WR -WeatherRouting Configuration.XML  menu
and pick  File > Open and select weatherroutingconfiguration.XML again
everything works fine, all settings are ready and we can just:

1. Make sure Options > Display > Graphics Acceleration is checked.
2. Enable Climatology, Grib_pi and WeatherRouting.
3. Check Wind on Climatology
4. Open the grib file Irma-Jose-2017090618.gfs.grib2
Located here: C:\ProgramData\opencpn\plugins\weather_routing\grib-sample\Irma-Jose-2017090618.gfs.grib2
5. Highlight the Configuration in the menu
6. Select "Compute"

**Comment by rgleason** [comment]
I've solved the problem with the two routings. I had changed the"Interval" to be greater in two instances thinking it would not make a difference in "Completion" and would be illustrative!  ..  Guess what? It does. In fact I can get totally different optimized routings dependent on the interval, say 1hr vs 4hr with the exact same grib and climatology. It is kind of interesting.

I will repackage this stuff in the next two days, so all 5 configurations work. 
Next I'll need some help getting files installed and pathnames correct in the install.

**Comment by rgleason** [comment]
I found that example
This was one of the configurations that failed. I had changed the interval and not tested. Then I found out I could get two entirely diffferent routes with different intervals!  The smaller interval found a better route.
![screenshot 267](https://user-images.githubusercontent.com/2363959/30774907-f3ed9b6a-a057-11e7-8725-a678f73d03a9.png)
![screenshot 266](https://user-images.githubusercontent.com/2363959/30774910-faa7d2d6-a057-11e7-8e7f-3126877de0a9.png)

**Comment by rgleason** [comment]
I've added the "Weather-Routing-Setup configuration examples to the Manual.
There are some interesting things that happen with different time intervals.....see

Routes from Cape Canaveral...
https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:opencpn_user_manual:toolbar_buttons:plugins:weather:weather_routing#computation_of_routes_from_cape_canaveral_with_different_intervals

Computation of 5 Routes.... Examples.
https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:opencpn_user_manual:toolbar_buttons:plugins:weather:weather_routing#computation_of_5_routes

**Comment by rgleason** [comment]
See  [Beta-Weather-Routing-Setup adds Data files](https://github.com/rgleason/weather_routing_pi/releases) to download and try "weather_routing_pi-1.10-R-Setup-win32.exe"

Some of the initial startup pathnames need to be improved, but other than that it works well.

**Comment by seandepagnier** [comment]
Yes, well a small interval is basically required to route through
islands or rapidly changing conditions properly.

Why would you want to beat against a hurricane ??

**Comment by rgleason** [comment]
Sean,
The whole point of this is to have the program install in such a way that the user can do just a few things to install and setup (say 4 steps) and then be able to  "Compute" a 
"Configuration" and have it complete. 

Then when they are more familiar with the process, they can adjust just a few things and learn.

To do this I need your cooperation because I believe the default pathnames need to be established.

Would you like me to make a PR?

**Comment by rgleason** [comment]
This is working now with Many Many thanks to Stelian! #91
