### ISSUE TITLE
153 Errors in Windows

### ISSUE THREAD

**Issue by rgleason** [seandepagnier/weather_routing_pi#81]
#77 Merge Dan's changes    (which worked)
https://github.com/seandepagnier/weather_routing_pi/commit/f19fa9b1ce59e291ee2aa890dc0fe0485c8f3030

Since then there were 3  commits that make 153 Errors.  (I've tried to compile twice in two totally separate ways.

**Comment by rgleason** [comment]
Well, it used to work... before it was merged.

The "Fix" apparently did not Fix the problem.
Cloned SeanDepagnier's and built as standalone --153 Errors
Cloned TransmitterDan's and built as standalone -- 153 Errors 
I've done this more than six times different ways.  Cloning to a new location. Trying newest Opencpn.lib etc.

See attached please.  I am going to Unclose Issue #76  
[Errors-153.txt](https://github.com/seandepagnier/weather_routing_pi/files/1327546/Errors-153.txt)

**Comment by seandepagnier** [comment]
rick,

these are all linker errors.  You must not be linking with opencpn.lib correctly.

**Comment by rgleason** [comment]
Sean, you are exactly correct!   My head was beating against the wall here and I was hugely frustrated. This morning I discoverd I had mislabeled v4.2 as v4.8 opencpn.lib somehow!  It works much much better now. Thank you!

Now when I see many linker and lib errors like that,, I should know it is Opencpn.LIB problem.
Closing.
