### ISSUE TITLE
Polar Files: Editing Problems

### ISSUE THREAD

**Issue by rgleason** [seandepagnier/weather_routing_pi#98]
1.  When Editing a polar under Dimensions TAB, and I try to add a TWS column by adding it to the top right field, (say TWS-20-60.pol , and I  put "24"in the top right and then click "Add")  Then the "24"goes to the bottom of the list (all good).

2. Now I hit "SAVE" at the bottom and there is a blue spinner for many minutes and OpenCPN eventually crashes.  ( Think this might be because the program is trying to save to the ProgramFile (x86) folders! Rather than saving to the correct user folder  (C:/programdata/opencpn/plugins/weather_routing/polars)?  However if I make no changes and hit SAVE it works fine.

3. In the Dimension Tab the values should  lso automatically Save if I hit one of the other TABS too! But it does not.

**Comment by stelian42** [comment]
This is strange because I cannot reproduce it, neither on Linux or on Windows. Something broken in your install ?

**Comment by rgleason** [comment]
Using my 1.1102beta release, installed into a clean environment.
Note--After initialization I confirmed that the Polars TWS____.pol files install correctly and were the correct files.
![screenshot 108](https://user-images.githubusercontent.com/2363959/34261674-efe0e7b8-e637-11e7-9d86-cb97901b5053.png)

I don't believe anything is broken in my install. I believe something is broken in Edit Polar > Dimensions
I tried to ADD  8.0  in the TWS box on the right. The "8.0" got down to the bottom when I hit ADD, but when I hit SAVE, I got the blue circle and eventual crash.   --It appears to be having trouble SAVING!!

This is the fifth or sixth time this has happened.  STelian are you sure you tested the same thing????

Also there is NO way to CANCEL this action.

**Comment by rgleason** [comment]
Stelian provided me with the answer after hunting for the problem everywhere.
1. His version worked.
2. Then he tried my version on his win machine it worked.
3. Meanwhile I was checking my configuration for compiliing, tried his opencpn.lib, deleted wxrite and started over, checked my MSVC++ config and it compiled O fine, checked Norton Security and it was not locking the files, found I had the same files in buildwin and build as Stelian. --I was stumped!
4. The Stelian suggested using:

```
cmake -Wno-dev -G "Visual Studio 12 2013" -T "v120_xp" -D CMAKE_CXX_FLAGS=/MP -D CMAKE_C_FLAGS=/MP ..
cmake --build . --config release
cmake --build . --config debug
cpack

```
rather than  cmake -T v120_xp ..

which is what TDAN's BATCHUTIL uses.
This ended up recompiling every file, and was longer, so it fixed whatever was not right.

Thanks Stelian for all your help.
I am closing this.
